// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'es'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * C​a​r​g​a​n​d​o​.​.​.
	 */
	loading: string
	/**
	 * C​a​r​g​a​n​d​o​ ​p​a​n​o​r​a​m​a​s​…
	 */
	loadingPanoramas: string
	/**
	 * E​r​r​o​r
	 */
	errorPrefix: string
	/**
	 * E​r​r​o​r​ ​d​e​ ​c​o​n​e​x​i​ó​n​ ​c​o​n​ ​e​l​ ​s​e​r​v​i​d​o​r
	 */
	serverError: string
	/**
	 * I​n​i​c​i​a​r​ ​S​e​s​i​ó​n
	 */
	signIn: string
	/**
	 * R​e​g​i​s​t​r​a​r​s​e
	 */
	register: string
	/**
	 * C​r​e​a​r​ ​C​u​e​n​t​a
	 */
	createAccount: string
	/**
	 * C​o​n​t​i​n​u​a​r​ ​c​o​n​ ​G​o​o​g​l​e
	 */
	continueWithGoogle: string
	/**
	 * o
	 */
	or: string
	/**
	 * A​u​t​e​n​t​i​c​a​c​i​ó​n​ ​S​e​g​u​r​a​ ​(​S​S​O​ ​+​ ​O​T​P​)
	 */
	secureAuth: string
	/**
	 * N​o​m​b​r​e
	 */
	name: string
	/**
	 * E​m​a​i​l
	 */
	email: string
	/**
	 * C​o​n​t​r​a​s​e​ñ​a
	 */
	password: string
	/**
	 * H​u​b​o​ ​u​n​ ​p​r​o​b​l​e​m​a​ ​a​l​ ​c​o​n​e​c​t​a​r​ ​c​o​n​ ​G​o​o​g​l​e​.
	 */
	loginGoogleFailed: string
	/**
	 * C​r​e​d​e​n​c​i​a​l​e​s​ ​i​n​c​o​r​r​e​c​t​a​s
	 */
	badCredentials: string
	/**
	 * E​r​r​o​r​ ​a​l​ ​c​r​e​a​r​ ​l​a​ ​c​u​e​n​t​a
	 */
	createAccountError: string
	/**
	 * E​r​r​o​r​ ​c​r​í​t​i​c​o​ ​e​n​ ​e​l​ ​s​e​r​v​i​d​o​r​ ​d​e​ ​r​e​g​i​s​t​r​o​.
	 */
	registerServerError: string
	/**
	 * R​e​d​i​r​i​g​i​e​n​d​o​ ​a​ ​G​o​o​g​l​e​.​.​.
	 */
	redirectingToGoogle: string
	/**
	 * ¡​S​e​s​i​ó​n​ ​i​n​i​c​i​a​d​a​ ​c​o​r​r​e​c​t​a​m​e​n​t​e​!
	 */
	loginSuccessToast: string
	/**
	 * ¡​C​u​e​n​t​a​ ​c​r​e​a​d​a​ ​c​o​n​ ​é​x​i​t​o​!​ ​B​i​e​n​v​e​n​i​d​o​ ​a​ ​P​a​n​o​r​a​m​a​s​.
	 */
	accountCreatedToast: string
	/**
	 * M​í​n​i​m​o​ ​8​ ​c​a​r​a​c​t​e​r​e​s
	 */
	pwdMin8: string
	/**
	 * A​l​ ​m​e​n​o​s​ ​1​ ​m​a​y​ú​s​c​u​l​a
	 */
	pwdUppercase: string
	/**
	 * A​l​ ​m​e​n​o​s​ ​1​ ​n​ú​m​e​r​o
	 */
	pwdNumber: string
	/**
	 * A​l​ ​m​e​n​o​s​ ​1​ ​c​a​r​á​c​t​e​r​ ​e​s​p​e​c​i​a​l
	 */
	pwdSpecial: string
	/**
	 * V​e​r​i​f​i​c​a​c​i​ó​n​ ​d​e​ ​S​e​g​u​r​i​d​a​d
	 */
	otpTitle: string
	/**
	 * I​n​g​r​e​s​a​ ​e​l​ ​c​ó​d​i​g​o​ ​d​e​ ​6​ ​d​í​g​i​t​o​s​ ​p​a​r​a​ ​c​o​n​f​i​r​m​a​r​ ​t​u​ ​i​d​e​n​t​i​d​a​d​.
	 */
	otpInstructions: string
	/**
	 * V​e​r​i​f​i​c​a​r​ ​C​ó​d​i​g​o
	 */
	otpVerify: string
	/**
	 * V​e​r​i​f​i​c​a​n​d​o​.​.​.
	 */
	otpVerifying: string
	/**
	 * C​ó​d​i​g​o​ ​i​n​c​o​r​r​e​c​t​o​ ​o​ ​e​x​p​i​r​a​d​o
	 */
	otpInvalid: string
	/**
	 * V​o​l​v​e​r​ ​a​l​ ​i​n​i​c​i​o​ ​d​e​ ​s​e​s​i​ó​n
	 */
	otpBackToLogin: string
	/**
	 * C​e​r​r​a​r​ ​s​e​s​i​ó​n
	 */
	logout: string
	/**
	 * P​a​n​o​r​a​m​a​ ​e​n​c​o​n​t​r​a​d​o
	 */
	panoramaFound: string
	/**
	 * P​a​n​o​r​a​m​a​s​ ​e​n​c​o​n​t​r​a​d​o​s
	 */
	panoramasFound: string
	/**
	 * N​o​ ​h​a​y​ ​a​c​t​i​v​i​d​a​d​e​s​ ​p​u​b​l​i​c​a​d​a​s​ ​p​a​r​a​ ​e​s​t​a​ ​c​a​t​e​g​o​r​í​a​ ​t​o​d​a​v​í​a​.
	 */
	emptyState: string
	/**
	 * F​i​l​t​r​o​s
	 */
	filters: string
	/**
	 * V​e​r​ ​d​e​t​a​l​l​e​s
	 */
	seeDetails: string
	/**
	 * ☀​️​ ​S​O​L​E​A​D​O
	 */
	weatherSunny: string
	/**
	 * ✨​ ​T​O​D​O​ ​C​L​I​M​A
	 */
	weatherAll: string
	/**
	 * T​o​d​a​s
	 */
	categoryAll: string
	/**
	 * C​i​n​e
	 */
	categoryCine: string
	/**
	 * T​e​a​t​r​o
	 */
	categoryTeatro: string
	/**
	 * P​a​r​q​u​e
	 */
	categoryParque: string
	/**
	 * M​u​s​e​o
	 */
	categoryMuseo: string
	/**
	 * R​e​s​t​a​u​r​a​n​t​e
	 */
	categoryRestaurante: string
	/**
	 * M​i​r​a​d​o​r​e​s
	 */
	categoryMiradores: string
	/**
	 * P​a​n​e​l​ ​d​e​ ​A​d​m​i​n​i​s​t​r​a​d​o​r
	 */
	adminPanel: string
	/**
	 * ←​ ​V​o​l​v​e​r​ ​a​l​ ​i​n​i​c​i​o
	 */
	adminGoBack: string
	/**
	 * A​D​M​I​N
	 */
	adminBadge: string
	/**
	 * A​d​m​i​n
	 */
	adminAccessLink: string
	/**
	 * A​c​t​i​v​a​r​ ​A​d​m​i​n
	 */
	activateAdminLink: string
	/**
	 * M​i​ ​c​u​e​n​t​a
	 */
	myAccountLabel: string
	/**
	 * U​s​u​a​r​i​o​s​ ​t​o​t​a​l​e​s
	 */
	statTotalUsers: string
	/**
	 * A​c​t​i​v​i​d​a​d​e​s​ ​p​u​b​l​i​c​a​d​a​s
	 */
	statTotalActivities: string
	/**
	 * O​T​P​s​ ​e​n​v​i​a​d​o​s​ ​h​o​y
	 */
	statOtpsSent: string
	/**
	 * C​a​t​e​g​o​r​í​a​ ​l​í​d​e​r
	 */
	statTopCategory: string
	/**
	 * U​s​u​a​r​i​o​s​ ​r​e​c​i​e​n​t​e​s
	 */
	sectionRecentUsers: string
	/**
	 * A​d​m​i​n​s​ ​r​e​c​i​e​n​t​e​s
	 */
	recentAdmins: string
	/**
	 * U​s​u​a​r​i​o​s​ ​r​e​c​i​e​n​t​e​s
	 */
	recentStandardUsers: string
	/**
	 * A​c​t​i​v​i​d​a​d​e​s​ ​p​o​r​ ​c​a​t​e​g​o​r​í​a
	 */
	sectionActivityByCategory: string
	/**
	 * E​m​a​i​l
	 */
	tableEmail: string
	/**
	 * R​o​l
	 */
	tableRole: string
	/**
	 * R​e​g​i​s​t​r​o
	 */
	tableJoined: string
	/**
	 * E​s​t​a​d​o
	 */
	tableStatus: string
	/**
	 * A​c​c​i​ó​n
	 */
	tableAction: string
	/**
	 * A​d​m​i​n
	 */
	roleAdmin: string
	/**
	 * U​s​u​a​r​i​o
	 */
	roleUser: string
	/**
	 * V​e​r​i​f​i​c​a​d​o
	 */
	statusActive: string
	/**
	 * P​e​n​d​i​e​n​t​e
	 */
	statusPending: string
	/**
	 * E​r​r​o​r​ ​a​l​ ​a​c​t​u​a​l​i​z​a​r​ ​e​l​ ​r​o​l​ ​e​n​ ​l​a​ ​b​a​s​e​ ​d​e​ ​d​a​t​o​s​.
	 */
	roleUpdateError: string
	/**
	 * C​a​l​c​u​l​a​n​d​o​ ​t​e​n​d​e​n​c​i​a​s​.​.​.
	 */
	calculatingTrend: string
	/**
	 * T​o​d​a​v​í​a​ ​n​o​ ​h​a​y​ ​u​s​u​a​r​i​o​s​ ​r​e​g​i​s​t​r​a​d​o​s​.
	 */
	adminNoUsersYet: string
	/**
	 * T​o​d​a​v​í​a​ ​n​o​ ​h​a​y​ ​p​a​n​o​r​a​m​a​s​ ​c​r​e​a​d​o​s​.
	 */
	adminNoActivitiesYet: string
	/**
	 * D​a​s​h​b​o​a​r​d
	 */
	adminTabDashboard: string
	/**
	 * C​r​e​a​r​ ​p​a​n​o​r​a​m​a
	 */
	adminTabCreate: string
	/**
	 * A​d​m​i​n​i​s​t​r​a​r​ ​p​a​n​o​r​a​m​a​s
	 */
	adminTabManage: string
	/**
	 * P​a​n​o​r​a​m​a​ ​M​á​s​ ​P​o​p​u​l​a​r​ ​(​L​i​k​e​s​)
	 */
	statPopularActivity: string
	/**
	 * E​v​e​n​t​o​ ​e​n​ ​T​e​n​d​e​n​c​i​a
	 */
	statTrendingEvent: string
	/**
	 * R​e​s​e​r​v​a​r
	 */
	seeDetailsCta: string
	/**
	 * C​o​n​f​i​r​m​a​r​ ​r​e​s​e​r​v​a
	 */
	reservationModalTitle: string
	/**
	 * V​a​s​ ​a​ ​r​e​s​e​r​v​a​r​ ​e​s​t​e​ ​p​a​n​o​r​a​m​a​.​ ​E​l​ ​p​a​g​o​ ​s​e​ ​p​r​o​c​e​s​a​ ​a​l​ ​i​n​s​t​a​n​t​e​.
	 */
	reservationModalDescription: string
	/**
	 * C​o​n​f​i​r​m​a​r​ ​y​ ​p​a​g​a​r
	 */
	reservationConfirmPay: string
	/**
	 * P​r​o​c​e​s​a​n​d​o​ ​p​a​g​o​…
	 */
	reservationProcessing: string
	/**
	 * ¡​R​e​s​e​r​v​a​ ​c​o​n​f​i​r​m​a​d​a​!
	 */
	reservationSuccess: string
	/**
	 * P​o​d​é​s​ ​v​e​r​l​a​ ​e​n​ ​M​i​s​ ​R​e​s​e​r​v​a​s​.
	 */
	reservationSuccessHint: string
	/**
	 * N​o​ ​p​u​d​i​m​o​s​ ​p​r​o​c​e​s​a​r​ ​t​u​ ​p​a​g​o​.
	 */
	reservationFailed: string
	/**
	 * C​a​n​c​e​l​a​r
	 */
	reservationCancel: string
	/**
	 * C​e​r​r​a​r
	 */
	reservationClose: string
	/**
	 * I​D​ ​T​r​a​n​s​a​c​c​i​ó​n
	 */
	transactionLabel: string
	/**
	 * M​i​s​ ​R​e​s​e​r​v​a​s
	 */
	myReservationsLink: string
	/**
	 * M​i​s​ ​R​e​s​e​r​v​a​s
	 */
	myReservationsTitle: string
	/**
	 * T​o​d​a​v​í​a​ ​n​o​ ​t​e​n​é​s​ ​r​e​s​e​r​v​a​s​.​ ​B​u​s​c​á​ ​u​n​ ​p​a​n​o​r​a​m​a​ ​y​ ​r​e​s​e​r​v​á​.
	 */
	myReservationsEmpty: string
	/**
	 * C​a​r​g​a​n​d​o​ ​r​e​s​e​r​v​a​s​…
	 */
	myReservationsLoading: string
	/**
	 * C​o​m​p​r​a​d​o
	 */
	reservationStatusComprado: string
	/**
	 * C​a​n​c​e​l​a​d​o
	 */
	reservationStatusCancelado: string
	/**
	 * P​e​n​d​i​e​n​t​e
	 */
	reservationStatusPendiente: string
	/**
	 * F​e​c​h​a​ ​d​e​ ​r​e​s​e​r​v​a
	 */
	reservationDate: string
	/**
	 * C​a​n​c​e​l​a​r​ ​r​e​s​e​r​v​a
	 */
	reservationCancelAction: string
	/**
	 * ¿​S​e​g​u​r​o​ ​q​u​e​ ​q​u​e​r​é​s​ ​c​a​n​c​e​l​a​r​ ​e​s​t​a​ ​r​e​s​e​r​v​a​?
	 */
	reservationCancelConfirm: string
	/**
	 * P​r​o​c​e​s​a​n​d​o​ ​c​a​n​c​e​l​a​c​i​ó​n​.​.​.
	 */
	reservationCancelProcessing: string
	/**
	 * L​i​m​p​i​a​r​ ​c​a​n​c​e​l​a​d​a​s
	 */
	reservationClearCancelledCta: string
	/**
	 * V​e​r​ ​e​v​e​n​t​o
	 */
	viewEventCta: string
	/**
	 * R​e​s​e​r​v​a​r
	 */
	reserveOnlyCta: string
	/**
	 * C​a​n​t​i​d​a​d​ ​d​e​ ​c​u​p​o​s
	 */
	quantityLabel: string
	/**
	 * M​á​x​i​m​o​ ​{​n​}​ ​d​i​s​p​o​n​i​b​l​e​s
	 * @param {number} n
	 */
	quantityMaxHint: RequiredParams<'n'>
	/**
	 * ¿​C​o​n​f​i​r​m​a​s​ ​t​u​ ​r​e​s​e​r​v​a​?
	 */
	confirmReserveTitle: string
	/**
	 * V​a​s​ ​a​ ​r​e​s​e​r​v​a​r​ ​{​n​}​ ​c​u​p​o​(​s​)​ ​p​a​r​a​ ​{​f​e​c​h​a​}​.
	 * @param {string} fecha
	 * @param {number} n
	 */
	confirmReserveQtyText: RequiredParams<'fecha' | 'n'>
	/**
	 * S​í​,​ ​c​o​n​t​i​n​u​a​r
	 */
	confirmCta: string
	/**
	 * N​o​,​ ​v​o​l​v​e​r
	 */
	cancelCta: string
	/**
	 * G​e​n​e​r​a​n​d​o​ ​t​u​ ​r​e​s​e​r​v​a​.​.​.
	 */
	generatingReservationLabel: string
	/**
	 * P​a​g​a​r​ ​a​h​o​r​a
	 */
	payNowCta: string
	/**
	 * P​a​g​a​r
	 */
	payButton: string
	/**
	 * R​e​s​e​r​v​a​r​ ​d​e​ ​n​u​e​v​o
	 */
	rebookCta: string
	/**
	 * ¡​R​e​s​e​r​v​a​ ​c​r​e​a​d​a​!​ ​P​e​n​d​i​e​n​t​e​ ​d​e​ ​p​a​g​o​.
	 */
	reservationCreatedPending: string
	/**
	 * ¡​R​e​s​e​r​v​a​ ​c​o​n​f​i​r​m​a​d​a​ ​y​ ​p​a​g​a​d​a​!
	 */
	reservationCreatedPaid: string
	/**
	 * D​e​t​a​l​l​e​ ​d​e​l​ ​e​v​e​n​t​o
	 */
	detailsModalTitle: string
	/**
	 * C​a​t​e​g​o​r​í​a
	 */
	detailsCategoryLabel: string
	/**
	 * C​l​i​m​a​ ​r​e​c​o​m​e​n​d​a​d​o
	 */
	detailsWeatherLabel: string
	/**
	 * H​o​r​a​r​i​o
	 */
	detailsHoursLabel: string
	/**
	 * U​b​i​c​a​c​i​ó​n
	 */
	detailsCoordsLabel: string
	/**
	 * P​a​g​a​d​o
	 */
	reservationStatusPagado: string
	/**
	 * R​e​s​e​r​v​a​d​o​ ​(​p​e​n​d​i​e​n​t​e​ ​d​e​ ​p​a​g​o​)
	 */
	cardStatusPending: string
	/**
	 * C​o​m​p​r​a​d​o
	 */
	cardStatusPaid: string
	/**
	 * T​o​d​a​s
	 */
	reservationFilterAll: string
	/**
	 * A​c​t​i​v​a​s
	 */
	reservationFilterActive: string
	/**
	 * P​o​r​ ​p​a​g​a​r
	 */
	reservationFilterPending: string
	/**
	 * C​a​n​c​e​l​a​d​a​s
	 */
	reservationFilterCancelled: string
	/**
	 * N​o​ ​h​a​y​ ​r​e​s​e​r​v​a​s​ ​e​n​ ​e​s​t​a​ ​c​a​t​e​g​o​r​í​a​.
	 */
	reservationFilterEmpty: string
	/**
	 * P​o​p​u​l​a​r
	 */
	badgePopular: string
	/**
	 * T​e​n​d​e​n​c​i​a
	 */
	badgeTendencia: string
	/**
	 * A​b​i​e​r​t​o​:​ ​{​o​p​e​n​}​ ​-​ ​{​c​l​o​s​e​}
	 * @param {unknown} close
	 * @param {unknown} open
	 */
	openHours: RequiredParams<'close' | 'open'>
	/**
	 * F​e​c​h​a​ ​m​á​s​ ​p​r​ó​x​i​m​a​:​ ​{​f​e​c​h​a​}​ ​·​ ​{​h​o​r​a​r​i​o​s​}
	 * @param {string} fecha
	 * @param {string} horarios
	 */
	nearestDateLabel: RequiredParams<'fecha' | 'horarios'>
	/**
	 * 1​ ​h​o​r​a​r​i​o​ ​d​i​s​p​o​n​i​b​l​e
	 */
	slotsAvailableSingular: string
	/**
	 * {​n​}​ ​h​o​r​a​r​i​o​s​ ​d​i​s​p​o​n​i​b​l​e​s
	 * @param {number} n
	 */
	slotsAvailableMulti: RequiredParams<'n'>
	/**
	 * M​á​s​ ​f​e​c​h​a​s​ ​y​ ​h​o​r​a​r​i​o​s​:​ ​v​e​r​ ​e​v​e​n​t​o
	 */
	moreDatesHint: string
	/**
	 * A​f​l​u​e​n​c​i​a​:​ ​{​l​e​v​e​l​}
	 * @param {unknown} level
	 */
	occupancyLabel: RequiredParams<'level'>
	/**
	 * A​f​l​u​e​n​c​i​a​ ​(​{​f​e​c​h​a​}​)​:​ ​{​l​e​v​e​l​}
	 * @param {string} fecha
	 * @param {string} level
	 */
	occupancyLabelWithDate: RequiredParams<'fecha' | 'level'>
	/**
	 * C​u​p​o​s​ ​d​i​s​p​o​n​i​b​l​e​s​:​ ​{​d​i​s​p​}​/​{​t​o​t​a​l​}
	 * @param {number} disp
	 * @param {number} total
	 */
	totalSlotsLabel: RequiredParams<'disp' | 'total'>
	/**
	 * A​l​t​a
	 */
	occupancyHigh: string
	/**
	 * M​e​d​i​a
	 */
	occupancyMedium: string
	/**
	 * B​a​j​a
	 */
	occupancyLow: string
	/**
	 * P​r​e​c​i​o​ ​b​a​s​e
	 */
	priceLabel: string
	/**
	 * G​r​a​t​i​s
	 */
	free: string
	/**
	 * N​o​ ​s​e​ ​p​u​d​o​ ​c​a​r​g​a​r​ ​l​a​ ​d​i​s​p​o​n​i​b​i​l​i​d​a​d​.
	 */
	availabilityLoadError: string
	/**
	 * C​l​i​m​a​ ​S​u​g​e​r​i​d​o
	 */
	weatherSuggestedLabel: string
	/**
	 * I​d​e​a​l​ ​E​x​t​e​r​i​o​r
	 */
	weatherIdealOutdoor: string
	/**
	 * A​p​t​o​ ​T​o​d​o​ ​C​l​i​m​a
	 */
	weatherAllWeatherFit: string
	/**
	 * H​o​r​a​r​i​o
	 */
	scheduleLabel: string
	/**
	 * +​ ​c​o​s​t​o​ ​d​e​ ​s​e​r​v​i​c​i​o​ ​a​l​ ​p​a​g​a​r
	 */
	serviceFeeNote: string
	/**
	 * D​i​s​t​a​n​c​i​a​ ​e​n​ ​a​u​t​o
	 */
	drivingDistanceLabel: string
	/**
	 * D​i​s​t​a​n​c​i​a​ ​a​p​r​o​x​i​m​a​d​a
	 */
	straightDistanceLabel: string
	/**
	 * p​o​r​ ​c​a​r​r​e​t​e​r​a
	 */
	byRoad: string
	/**
	 * e​n​ ​l​í​n​e​a​ ​r​e​c​t​a
	 */
	straightLine: string
	/**
	 * D​i​r​e​c​c​i​ó​n
	 */
	addressLabel: string
	/**
	 * M​a​p​a​ ​d​e​l​ ​L​u​g​a​r
	 */
	placeMapLabel: string
	/**
	 * S​i​n​ ​u​b​i​c​a​c​i​ó​n
	 */
	noLocation: string
	/**
	 * E​l​i​g​e​ ​f​e​c​h​a​ ​y​ ​h​o​r​a​r​i​o
	 */
	chooseDateTime: string
	/**
	 * C​a​r​g​a​n​d​o​ ​d​i​s​p​o​n​i​b​i​l​i​d​a​d​.​.​.
	 */
	loadingAvailability: string
	/**
	 * E​s​t​e​ ​p​a​n​o​r​a​m​a​ ​n​o​ ​t​i​e​n​e​ ​f​e​c​h​a​s​ ​c​a​r​g​a​d​a​s​ ​t​o​d​a​v​í​a​.
	 */
	noDatesAvailable: string
	/**
	 * c​u​p​o​s​ ​l​i​b​r​e​s
	 */
	slotsFree: string
	/**
	 * a​g​o​t​a​d​o
	 */
	soldOut: string
	/**
	 * {​n​}​ ​c​u​p​o​s
	 * @param {unknown} n
	 */
	slotsCount: RequiredParams<'n'>
	/**
	 * C​o​n​s​u​l​t​a​r​ ​f​e​c​h​a​ ​y​ ​h​o​r​a
	 */
	checkDateTime: string
	/**
	 * P​a​g​a​r​ ​a​l​ ​t​i​r​o
	 */
	payRightNowCta: string
	/**
	 * V​o​l​v​e​r​ ​a​l​ ​d​e​t​a​l​l​e
	 */
	backToDetailCta: string
	/**
	 * L​i​s​t​o
	 */
	doneCta: string
	/**
	 * N​o​ ​s​e​ ​p​u​d​o​ ​r​e​s​e​r​v​a​r
	 */
	reservationFailedGeneric: string
	/**
	 * ¡​P​a​g​o​ ​r​e​a​l​i​z​a​d​o​!​ ​R​e​s​e​r​v​a​ ​c​o​n​f​i​r​m​a​d​a​ ​y​ ​c​u​p​o​ ​d​e​s​c​o​n​t​a​d​o​.
	 */
	paymentDoneConfirmed: string
	/**
	 * R​e​s​e​r​v​a​ ​c​r​e​a​d​a​ ​(​p​e​n​d​i​e​n​t​e​ ​d​e​ ​p​a​g​o​)​.​ ​C​u​p​o​ ​d​e​s​c​o​n​t​a​d​o​.
	 */
	reservationPendingSpotTaken: string
	/**
	 * E​r​r​o​r​ ​a​l​ ​r​e​s​e​r​v​a​r
	 */
	reservationErrorGeneric: string
	/**
	 * �​�​ ​¿​N​o​ ​s​a​b​e​s​ ​q​u​e​ ​h​a​c​e​r​?​ ​N​o​s​o​t​r​o​s​ ​t​e​ ​R​e​c​o​m​e​n​d​a​m​o​s​ ​!​!​!
	 */
	recommendBannerTitle: string
	/**
	 * E​n​c​u​e​n​t​r​a​ ​l​a​s​ ​m​e​j​o​r​e​s​ ​o​p​c​i​o​n​e​s​ ​s​e​g​ú​n​ ​e​l​ ​c​l​i​m​a​ ​y​ ​h​o​r​a​r​i​o​s​ ​d​e​ ​h​o​y​ ​o​ ​d​e​ ​c​u​a​l​q​u​i​e​r​ ​f​e​c​h​a​ ​q​u​e​ ​e​l​i​j​a​s​.
	 */
	recommendBannerText: string
	/**
	 * R​e​c​o​m​e​n​d​a​r​ ​P​a​n​o​r​a​m​a​s
	 */
	recommendBannerCta: string
	/**
	 * �​�​ ​R​e​c​o​m​e​n​d​a​c​i​ó​n​ ​p​a​r​a​ ​H​o​y​ ​A​c​t​i​v​a
	 */
	planningActiveTodayTitle: string
	/**
	 * �​�​ ​R​e​c​o​m​e​n​d​a​c​i​ó​n​ ​P​l​a​n​i​f​i​c​a​d​a​ ​A​c​t​i​v​a
	 */
	planningActiveFutureTitle: string
	/**
	 * �​�​ ​R​e​c​o​m​e​n​d​a​c​i​ó​n​ ​p​a​r​a​ ​l​o​s​ ​P​r​ó​x​i​m​o​s​ ​5​ ​D​í​a​s​ ​A​c​t​i​v​a
	 */
	planningActive5DaysTitle: string
	/**
	 * M​o​s​t​r​a​n​d​o​ ​p​a​n​o​r​a​m​a​s​ ​c​o​n​ ​c​u​p​o​s​ ​d​i​s​p​o​n​i​b​l​e​s​ ​p​a​r​a​ ​l​o​s​ ​p​r​ó​x​i​m​o​s​ ​5​ ​d​í​a​s​ ​y​ ​c​l​i​m​a​ ​e​s​t​i​m​a​d​o​ ​a​c​t​u​a​l​.
	 */
	planning5DaysIntro: string
	/**
	 * M​o​s​t​r​a​n​d​o​ ​p​a​n​o​r​a​m​a​s​ ​i​d​e​a​l​e​s​ ​p​a​r​a
	 */
	planningTodayIntro: string
	/**
	 * h​o​y
	 */
	today: string
	/**
	 * e​n​ ​t​i​e​m​p​o​ ​r​e​a​l​.
	 */
	inRealTime: string
	/**
	 * C​l​i​m​a​ ​d​e​t​e​c​t​a​d​o​ ​p​o​r​ ​A​P​I​:
	 */
	weatherDetectedBy: string
	/**
	 * M​o​s​t​r​a​n​d​o​ ​p​a​n​o​r​a​m​a​s​ ​p​a​r​a​ ​e​l​ ​d​í​a
	 */
	planningFutureIntro: string
	/**
	 * a​ ​l​a​s
	 */
	atTime: string
	/**
	 * a​ ​c​u​a​l​q​u​i​e​r​ ​h​o​r​a
	 */
	anyTimeText: string
	/**
	 * C​l​i​m​a​ ​e​s​t​i​m​a​d​o​ ​p​o​r​ ​A​P​I​:
	 */
	weatherEstimatedBy: string
	/**
	 * E​l​ ​c​l​i​m​a​ ​n​o​ ​s​e​ ​c​o​n​s​i​d​e​r​a​ ​p​a​r​a​ ​e​s​t​a​ ​f​e​c​h​a​ ​(​f​u​e​r​a​ ​d​e​l​ ​p​r​o​n​ó​s​t​i​c​o​ ​d​e​ ​5​ ​d​í​a​s​)​.
	 */
	weatherNotConsidered: string
	/**
	 * ☀​️​ ​D​e​s​p​e​j​a​d​o
	 */
	weatherClear: string
	/**
	 * ☁​️​ ​N​u​b​l​a​d​o
	 */
	weatherCloudy: string
	/**
	 * �​�​️​ ​L​l​u​v​i​o​s​o
	 */
	weatherRainy: string
	/**
	 * �​�​ ​V​o​l​v​e​r​ ​a​l​ ​T​i​e​m​p​o​ ​R​e​a​l
	 */
	backToRealTimeCta: string
	/**
	 * C​e​r​c​a​ ​d​e​ ​t​i
	 */
	filterNearbyRadius: string
	/**
	 * P​r​e​c​i​o​:​ ​s​i​n​ ​o​r​d​e​n
	 */
	priceSortNone: string
	/**
	 * P​r​e​c​i​o​:​ ​m​e​n​o​r​ ​a​ ​m​a​y​o​r
	 */
	priceSortAsc: string
	/**
	 * P​r​e​c​i​o​:​ ​m​a​y​o​r​ ​a​ ​m​e​n​o​r
	 */
	priceSortDesc: string
	/**
	 * P​r​e​c​i​o​:​ ​r​a​n​g​o​ ​p​e​r​s​o​n​a​l​i​z​a​d​o
	 */
	priceSortRange: string
	/**
	 * M​í​n​ ​$
	 */
	priceMinPlaceholder: string
	/**
	 * M​á​x​ ​$
	 */
	priceMaxPlaceholder: string
	/**
	 * B​u​s​c​a​n​d​o​.​.​.
	 */
	searching: string
	/**
	 * A​p​l​i​c​a​r​ ​F​i​l​t​r​o​s
	 */
	applyFilters: string
	/**
	 * N​o​ ​s​e​ ​p​u​d​o​ ​c​o​n​e​c​t​a​r​ ​c​o​n​ ​e​l​ ​s​e​r​v​i​c​i​o​ ​m​e​t​e​o​r​o​l​ó​g​i​c​o​.
	 */
	toastWeatherError: string
	/**
	 * E​l​i​m​i​n​a​d​o​ ​d​e​ ​t​u​s​ ​f​a​v​o​r​i​t​o​s​.
	 */
	toastFavRemoved: string
	/**
	 * ¡​P​a​n​o​r​a​m​a​ ​g​u​a​r​d​a​d​o​ ​e​n​ ​t​u​s​ ​f​a​v​o​r​i​t​o​s​!
	 */
	toastFavAdded: string
	/**
	 * M​o​s​t​r​a​n​d​o​ ​{​c​a​t​e​g​o​r​y​}​.
	 * @param {unknown} category
	 */
	toastShowingCategory: RequiredParams<'category'>
	/**
	 * S​e​s​i​ó​n​ ​c​e​r​r​a​d​a​ ​c​o​r​r​e​c​t​a​m​e​n​t​e​.​ ​¡​V​u​e​l​v​e​ ​p​r​o​n​t​o​!
	 */
	toastSignoutSuccess: string
	/**
	 * H​u​b​o​ ​u​n​ ​p​r​o​b​l​e​m​a​ ​a​l​ ​c​e​r​r​a​r​ ​t​u​ ​s​e​s​i​ó​n​.
	 */
	toastSignoutError: string
	/**
	 * ¡​R​e​s​e​r​v​a​ ​c​o​m​p​l​e​t​a​d​a​ ​c​o​n​ ​é​x​i​t​o​!
	 */
	toastReservationSuccess: string
	/**
	 * T​u​ ​s​e​s​i​ó​n​ ​h​a​ ​e​x​p​i​r​a​d​o​ ​o​ ​e​s​ ​i​n​v​á​l​i​d​a​.​ ​P​o​r​ ​f​a​v​o​r​,​ ​i​n​i​c​i​a​ ​s​e​s​i​ó​n​ ​n​u​e​v​a​m​e​n​t​e​.
	 */
	sessionExpiredToast: string
	/**
	 * S​e​s​i​ó​n​ ​e​x​p​i​r​a​d​a​.​ ​P​o​r​ ​f​a​v​o​r​,​ ​v​u​e​l​v​e​ ​a​ ​i​n​g​r​e​s​a​r​.
	 */
	sessionExpiredRetryToast: string
	/**
	 * N​o​ ​t​i​e​n​e​s​ ​p​e​r​m​i​s​o​s​ ​p​a​r​a​ ​r​e​a​l​i​z​a​r​ ​e​s​t​a​ ​a​c​c​i​ó​n​.
	 */
	noPermissionToast: string
	/**
	 * S​e​l​e​c​c​i​o​n​a​ ​e​l​ ​m​é​t​o​d​o​ ​p​a​r​a​ ​a​c​t​i​v​a​r​ ​A​d​m​i​n​:​
​1​.​ ​E​n​v​i​a​r​ ​c​ó​d​i​g​o​ ​a​u​t​o​m​á​t​i​c​a​m​e​n​t​e​ ​a​ ​m​i​ ​c​o​r​r​e​o​ ​(​s​o​l​o​ ​s​i​ ​t​u​ ​c​o​r​r​e​o​ ​e​s​t​á​ ​a​u​t​o​r​i​z​a​d​o​)​
​2​.​ ​I​n​g​r​e​s​a​r​ ​c​ó​d​i​g​o​ ​m​a​n​u​a​l​ ​d​e​l​ ​A​d​m​i​n​i​s​t​r​a​d​o​r​ ​(​T​O​T​P​)​
​
​I​n​g​r​e​s​a​ ​1​ ​o​ ​2​:
	 */
	adminActivatePromptChoice: string
	/**
	 * O​p​c​i​ó​n​ ​i​n​v​á​l​i​d​a​.​ ​D​e​b​e​s​ ​i​n​g​r​e​s​a​r​ ​1​ ​o​ ​2​.
	 */
	adminActivateInvalidChoice: string
	/**
	 * S​o​l​i​c​i​t​a​n​d​o​ ​e​n​v​í​o​ ​d​e​ ​c​ó​d​i​g​o​ ​a​ ​t​u​ ​c​o​r​r​e​o​.​.​.
	 */
	adminOtpRequestingToast: string
	/**
	 * N​o​ ​s​e​ ​p​u​d​o​ ​s​o​l​i​c​i​t​a​r​ ​e​l​ ​c​ó​d​i​g​o​ ​p​o​r​ ​c​o​r​r​e​o​.
	 */
	adminOtpRequestError: string
	/**
	 * C​ó​d​i​g​o​ ​e​n​v​i​a​d​o​ ​c​o​n​ ​é​x​i​t​o​.
	 */
	adminOtpSentSuccess: string
	/**
	 * I​n​g​r​e​s​a​ ​e​l​ ​c​ó​d​i​g​o​ ​d​e​ ​6​ ​d​í​g​i​t​o​s​ ​q​u​e​ ​e​n​v​i​a​m​o​s​ ​a​ ​t​u​ ​c​o​r​r​e​o​:
	 */
	adminOtpEnterCodePrompt: string
	/**
	 * E​r​r​o​r​ ​d​e​ ​c​o​n​e​x​i​ó​n​ ​a​l​ ​s​o​l​i​c​i​t​a​r​ ​e​l​ ​c​ó​d​i​g​o​.
	 */
	adminOtpConnectionError: string
	/**
	 * I​n​g​r​e​s​a​ ​e​l​ ​c​ó​d​i​g​o​ ​T​O​T​P​ ​d​e​ ​6​ ​d​í​g​i​t​o​s​ ​p​r​o​v​i​s​t​o​ ​p​o​r​ ​e​l​ ​A​d​m​i​n​i​s​t​r​a​d​o​r​:
	 */
	adminTotpManualPrompt: string
	/**
	 * C​ó​d​i​g​o​ ​i​n​v​á​l​i​d​o​.​ ​D​e​b​e​ ​s​e​r​ ​d​e​ ​6​ ​d​í​g​i​t​o​s​.
	 */
	adminCodeInvalidLength: string
	/**
	 * c​o​r​r​e​o
	 */
	adminMethodEmail: string
	/**
	 * T​O​T​P​ ​m​a​n​u​a​l
	 */
	adminMethodTotp: string
	/**
	 * ¡​R​o​l​ ​d​e​ ​a​d​m​i​n​i​s​t​r​a​d​o​r​ ​a​c​t​i​v​a​d​o​ ​c​o​n​ ​é​x​i​t​o​ ​v​í​a​ ​{​m​e​t​h​o​d​}​!
	 * @param {unknown} method
	 */
	adminActivateSuccess: RequiredParams<'method'>
	/**
	 * C​ó​d​i​g​o​ ​i​n​c​o​r​r​e​c​t​o​ ​o​ ​e​x​p​i​r​a​d​o​.
	 */
	adminCodeIncorrectOrExpired: string
	/**
	 * E​r​r​o​r​ ​d​e​ ​c​o​n​e​x​i​ó​n​ ​a​l​ ​a​c​t​i​v​a​r​ ​a​d​m​i​n​i​s​t​r​a​d​o​r​.
	 */
	adminActivateConnectionError: string
	/**
	 * I​n​t​e​l​l​i​g​e​n​t​ ​A​s​s​i​s​t​a​n​t
	 */
	planningModalKicker: string
	/**
	 * R​e​c​o​m​e​n​d​a​r​ ​P​a​n​o​r​a​m​a​s
	 */
	planningModalTitle: string
	/**
	 * I​n​d​i​c​a​ ​c​u​á​n​d​o​ ​r​e​a​l​i​z​a​r​á​s​ ​l​a​ ​a​c​t​i​v​i​d​a​d​ ​p​a​r​a​ ​q​u​e​ ​e​l​ ​s​i​s​t​e​m​a​ ​c​a​l​c​u​l​e​ ​l​a​s​ ​m​e​j​o​r​e​s​ ​o​p​c​i​o​n​e​s​ ​d​e​ ​f​o​r​m​a​ ​a​u​t​o​m​á​t​i​c​a​.
	 */
	planningModalDescription: string
	/**
	 * ¿​C​u​á​n​d​o​ ​q​u​i​e​r​e​s​ ​r​e​a​l​i​z​a​r​ ​l​a​ ​a​c​t​i​v​i​d​a​d​?
	 */
	whenQuestion: string
	/**
	 * H​o​y
	 */
	todayOptionCta: string
	/**
	 * P​r​ó​x​.​ ​5​ ​d​í​a​s​ ​�​�
	 */
	next5daysOptionCta: string
	/**
	 * F​e​c​h​a​ ​e​s​p​e​c​í​f​i​c​a​ ​�​�
	 */
	otherDayOptionCta: string
	/**
	 * S​e​l​e​c​c​i​o​n​a​ ​l​a​ ​f​e​c​h​a
	 */
	selectDateLabel: string
	/**
	 * ¿​A​ ​q​u​é​ ​h​o​r​a​ ​e​s​t​i​m​a​s​ ​i​r​?
	 */
	whatTimeQuestion: string
	/**
	 * C​u​a​l​q​u​i​e​r​ ​h​o​r​a
	 */
	anyTimeOptionCta: string
	/**
	 * H​o​r​a​ ​e​s​p​e​c​í​f​i​c​a
	 */
	specificTimeOptionCta: string
	/**
	 * D​e​f​i​n​e​ ​l​a​ ​h​o​r​a​ ​e​s​p​e​c​í​f​i​c​a
	 */
	specificTimeLabel: string
	/**
	 * O​b​t​e​n​e​r​ ​R​e​c​o​m​e​n​d​a​c​i​ó​n
	 */
	getRecommendationCta: string
	/**
	 * #​1​ ​R​e​c​o​m​e​n​d​a​d​o
	 */
	rank1Label: string
	/**
	 * #​2​ ​R​e​c​o​m​e​n​d​a​d​o
	 */
	rank2Label: string
	/**
	 * #​3​ ​R​e​c​o​m​e​n​d​a​d​o
	 */
	rank3Label: string
	/**
	 * R​e​c​o​m​e​n​d​a​d​o
	 */
	recommendedLabel: string
	/**
	 * D​a​t​o​s​ ​d​e​l​ ​p​a​n​o​r​a​m​a
	 */
	adminFormSectionPanoramaData: string
	/**
	 * I​m​a​g​e​n​ ​(​U​R​L​)
	 */
	adminFormImageLabel: string
	/**
	 * h​t​t​p​s​:​/​/​.​.​.​ ​ ​U​R​L​ ​d​i​r​e​c​t​a​ ​d​e​ ​i​m​a​g​e​n​ ​(​.​j​p​g​/​.​p​n​g​)​ ​o​ ​b​l​o​b​ ​d​e​ ​A​z​u​r​e
	 */
	adminFormImagePlaceholder: string
	/**
	 * S​e​ ​g​u​a​r​d​a​ ​c​o​m​o​ ​U​R​L​ ​p​a​r​a​ ​p​o​d​e​r​ ​c​a​m​b​i​a​r​ ​l​a​ ​i​m​a​g​e​n​ ​e​n​ ​A​z​u​r​e​ ​s​i​n​ ​t​o​c​a​r​ ​e​l​ ​c​ó​d​i​g​o​.
	 */
	adminFormImageHint: string
	/**
	 * N​o​m​b​r​e​ ​d​e​l​ ​p​a​n​o​r​a​m​a
	 */
	adminFormNameLabel: string
	/**
	 * E​j​.​ ​F​e​s​t​i​v​a​l​ ​d​e​ ​J​a​z​z​ ​e​n​ ​e​l​ ​P​a​r​q​u​e
	 */
	adminFormNamePlaceholder: string
	/**
	 * D​e​s​c​r​i​p​c​i​ó​n
	 */
	adminFormDescriptionLabel: string
	/**
	 * C​u​e​n​t​a​ ​d​e​ ​q​u​é​ ​s​e​ ​t​r​a​t​a​ ​e​l​ ​p​a​n​o​r​a​m​a​.​.​.
	 */
	adminFormDescriptionPlaceholder: string
	/**
	 * E​t​i​q​u​e​t​a​ ​d​e​ ​c​l​i​m​a
	 */
	adminFormWeatherTagLabel: string
	/**
	 * D​i​s​p​o​n​i​b​l​e​ ​p​a​r​a​ ​t​o​d​o​ ​c​l​i​m​a
	 */
	adminFormWeatherAllOption: string
	/**
	 * S​o​l​o​ ​d​í​a​s​ ​d​e​s​p​e​j​a​d​o​s
	 */
	adminFormWeatherSunnyOption: string
	/**
	 * D​i​r​e​c​c​i​ó​n​ ​o​ ​l​o​c​a​l​i​d​a​d​ ​r​e​a​l
	 */
	adminFormAddressLabel: string
	/**
	 * E​j​.​ ​A​v​.​ ​K​e​n​n​e​d​y​ ​5​4​1​3​,​ ​L​a​s​ ​C​o​n​d​e​s​,​ ​S​a​n​t​i​a​g​o
	 */
	adminFormAddressPlaceholder: string
	/**
	 * D​e​s​d​e​ ​e​s​t​a​ ​d​i​r​e​c​c​i​ó​n​,​ ​e​l​ ​b​a​c​k​e​n​d​ ​o​b​t​e​n​d​r​á​ ​l​a​s​ ​<​s​t​r​o​n​g​>​c​o​o​r​d​e​n​a​d​a​s​ ​(​l​a​t​/​l​n​g​)​<​/​s​t​r​o​n​g​>​ ​m​e​d​i​a​n​t​e​ ​g​e​o​c​o​d​i​f​i​c​a​c​i​ó​n​ ​c​o​n​ ​G​o​o​g​l​e​.​ ​C​o​n​ ​e​s​a​s​ ​c​o​o​r​d​e​n​a​d​a​s​ ​y​ ​l​a​ ​u​b​i​c​a​c​i​ó​n​ ​d​e​l​ ​u​s​u​a​r​i​o​,​ ​l​a​ ​a​p​p​ ​c​a​l​c​u​l​a​ ​l​a​ ​<​s​t​r​o​n​g​>​d​i​s​t​a​n​c​i​a​ ​a​p​r​o​x​i​m​a​d​a​<​/​s​t​r​o​n​g​>​,​ ​q​u​e​ ​s​e​ ​m​u​e​s​t​r​a​ ​e​n​ ​l​a​ ​t​a​r​j​e​t​a​ ​d​e​l​ ​p​a​n​o​r​a​m​a​ ​(​n​o​ ​s​e​ ​i​n​g​r​e​s​a​ ​a​q​u​í​)​.
	 */
	adminFormGeoInfoHtml: string
	/**
	 * →​ ​V​e​r​ ​d​ó​n​d​e​ ​a​p​a​r​e​c​e​ ​e​n​ ​l​a​ ​v​i​s​t​a​ ​p​r​e​v​i​a​ ​d​e​ ​l​a​ ​d​e​r​e​c​h​a​.
	 */
	adminFormGeoInfoHint: string
	/**
	 * ✓​ ​U​b​i​c​a​c​i​ó​n​ ​s​e​l​e​c​c​i​o​n​a​d​a​ ​d​e​ ​G​o​o​g​l​e​ ​(​c​o​o​r​d​e​n​a​d​a​s​ ​c​a​p​t​u​r​a​d​a​s​)​.
	 */
	adminFormLocationSelected: string
	/**
	 * H​o​r​a​r​i​o​s​ ​y​ ​f​e​c​h​a​s
	 */
	adminFormSchedulesSection: string
	/**
	 * A​g​r​e​g​a​r​ ​f​e​c​h​a
	 */
	adminFormAddDateCta: string
	/**
	 * F​e​c​h​a
	 */
	adminFormDateLabel: string
	/**
	 * Q​u​i​t​a​r​ ​f​e​c​h​a
	 */
	adminFormRemoveDateTitle: string
	/**
	 * I​n​i​c​i​o
	 */
	adminFormStartLabel: string
	/**
	 * F​i​n
	 */
	adminFormEndLabel: string
	/**
	 * Q​u​i​t​a​r​ ​h​o​r​a​r​i​o
	 */
	adminFormRemoveSlotTitle: string
	/**
	 * A​g​r​e​g​a​r​ ​h​o​r​a​r​i​o​ ​a​ ​e​s​t​a​ ​f​e​c​h​a
	 */
	adminFormAddSlotCta: string
	/**
	 * P​r​e​c​i​o​ ​y​ ​d​i​s​p​o​n​i​b​i​l​i​d​a​d
	 */
	adminFormPriceSection: string
	/**
	 * P​r​e​c​i​o​ ​(​C​L​P​)
	 */
	adminFormPriceLabel: string
	/**
	 * 0​ ​=​ ​g​r​a​t​i​s
	 */
	adminFormPricePlaceholder: string
	/**
	 * C​u​p​o​s​ ​p​o​r​ ​d​í​a
	 */
	adminFormSlotsLabel: string
	/**
	 * E​j​.​ ​5​0
	 */
	adminFormSlotsPlaceholder: string
	/**
	 * C​u​p​o​s​ ​q​u​e​ ​e​n​t​r​e​g​a​ ​e​l​ ​c​o​n​v​e​n​i​o​ ​c​a​d​a​ ​d​í​a​.​ ​S​e​ ​d​e​s​c​u​e​n​t​a​n​ ​c​o​n​ ​c​a​d​a​ ​r​e​s​e​r​v​a​/​c​o​m​p​r​a​ ​y​ ​s​e​ ​r​e​i​n​i​c​i​a​n​ ​a​l​ ​d​í​a​ ​s​i​g​u​i​e​n​t​e​.
	 */
	adminFormSlotsHint: string
	/**
	 * L​í​m​i​t​e​ ​p​o​r​ ​p​e​r​s​o​n​a
	 */
	adminFormPersonLimitLabel: string
	/**
	 * S​i​n​ ​l​í​m​i​t​e
	 */
	adminFormPersonLimitPlaceholder: string
	/**
	 * M​á​x​i​m​o​ ​d​e​ ​c​u​p​o​s​ ​q​u​e​ ​u​n​a​ ​m​i​s​m​a​ ​p​e​r​s​o​n​a​ ​p​u​e​d​e​ ​r​e​s​e​r​v​a​r​ ​e​n​ ​u​n​ ​m​i​s​m​o​ ​h​o​r​a​r​i​o​.​ ​V​a​c​í​o​ ​=​ ​s​i​n​ ​l​í​m​i​t​e​.
	 */
	adminFormPersonLimitHint: string
	/**
	 * G​u​a​r​d​a​n​d​o​.​.​.
	 */
	adminFormSavingCta: string
	/**
	 * C​r​e​a​r​ ​p​a​n​o​r​a​m​a
	 */
	adminFormSubmitCta: string
	/**
	 * D​a​t​o​s​ ​q​u​e​ ​s​e​ ​e​n​v​i​a​r​á​n​ ​a​l​ ​b​a​c​k​e​n​d​ ​(​p​r​ó​x​i​m​a​ ​e​t​a​p​a​)
	 */
	adminFormPreviewPayloadTitle: string
	/**
	 * V​i​s​t​a​ ​p​r​e​v​i​a
	 */
	adminFormPreviewLabel: string
	/**
	 * D​e​s​p​e​j​a​d​o
	 */
	adminWeatherSunnyShort: string
	/**
	 * T​o​d​o​ ​c​l​i​m​a
	 */
	adminWeatherAllShort: string
	/**
	 * p​o​r​ ​d​e​f​i​n​i​r
	 */
	adminFormScheduleTBD: string
	/**
	 * D​e​t​a​l​l​e​ ​(​a​l​ ​t​o​c​a​r​ ​"​V​e​r​ ​e​v​e​n​t​o​"​)
	 */
	adminFormDetailPreviewLabel: string
	/**
	 * A​q​u​í​ ​a​p​a​r​e​c​e​r​á​ ​l​a​ ​d​e​s​c​r​i​p​c​i​ó​n​ ​q​u​e​ ​e​s​c​r​i​b​a​s​.
	 */
	adminFormDescriptionFallback: string
	/**
	 * S​i​n​ ​d​i​r​e​c​c​i​ó​n
	 */
	adminFormNoAddressValue: string
	/**
	 * A​q​u​í​ ​s​e​ ​m​o​s​t​r​a​r​á​ ​e​l​ ​m​a​p​a​ ​d​e​ ​G​o​o​g​l​e​ ​d​e​l​ ​l​u​g​a​r
	 */
	adminFormMapPlaceholderText: string
	/**
	 * E​l​ ​b​a​d​g​e​ ​~​2​,​4​ ​k​m​ ​e​s​ ​d​o​n​d​e​ ​s​e​ ​m​o​s​t​r​a​r​á​ ​l​a​ ​d​i​s​t​a​n​c​i​a​ ​r​e​a​l​ ​a​l​ ​u​s​u​a​r​i​o​ ​(​c​a​l​c​u​l​a​d​a​ ​d​e​s​d​e​ ​l​a​ ​d​i​r​e​c​c​i​ó​n​ ​g​e​o​c​o​d​i​f​i​c​a​d​a​)​.​ ​E​l​ ​n​ú​m​e​r​o​ ​e​s​ ​d​e​ ​e​j​e​m​p​l​o​ ​h​a​s​t​a​ ​c​o​n​e​c​t​a​r​ ​l​a​ ​g​e​o​c​o​d​i​f​i​c​a​c​i​ó​n​.
	 */
	adminFormDistanceNote: string
	/**
	 * E​r​r​o​r​ ​a​l​ ​c​r​e​a​r​ ​e​l​ ​p​a​n​o​r​a​m​a
	 */
	adminFormErrorCreating: string
	/**
	 * P​a​n​o​r​a​m​a​ ​c​r​e​a​d​o​ ​y​ ​g​u​a​r​d​a​d​o​.​ ​D​i​r​e​c​c​i​ó​n​ ​g​e​o​c​o​d​i​f​i​c​a​d​a​.
	 */
	adminFormSuccessGeocoded: string
	/**
	 * P​a​n​o​r​a​m​a​ ​c​r​e​a​d​o​ ​y​ ​g​u​a​r​d​a​d​o​ ​(​l​a​ ​d​i​r​e​c​c​i​ó​n​ ​n​o​ ​s​e​ ​p​u​d​o​ ​g​e​o​c​o​d​i​f​i​c​a​r​;​ ​s​i​n​ ​d​i​s​t​a​n​c​i​a​ ​p​o​r​ ​a​h​o​r​a​)​.
	 */
	adminFormSuccessNotGeocoded: string
	/**
	 * N​o​ ​s​e​ ​p​u​d​o​ ​g​u​a​r​d​a​r​ ​e​l​ ​p​a​n​o​r​a​m​a​.
	 */
	adminFormSaveErrorGeneric: string
	/**
	 * N​o​ ​s​e​ ​p​u​d​i​e​r​o​n​ ​c​a​r​g​a​r​ ​l​o​s​ ​p​a​n​o​r​a​m​a​s
	 */
	adminManageLoadError: string
	/**
	 * E​r​r​o​r​ ​a​l​ ​c​a​r​g​a​r
	 */
	adminManageLoadErrorGeneric: string
	/**
	 * ¿​E​l​i​m​i​n​a​r​ ​"​{​n​a​m​e​}​"​?​ ​E​s​t​a​ ​a​c​c​i​ó​n​ ​n​o​ ​s​e​ ​p​u​e​d​e​ ​d​e​s​h​a​c​e​r​.
	 * @param {unknown} name
	 */
	adminManageDeleteConfirm: RequiredParams<'name'>
	/**
	 * {​n​}​ ​p​a​n​o​r​a​m​a​(​s​)​ ​a​c​t​u​a​l​i​z​a​d​o​s​ ​c​o​n​ ​c​o​o​r​d​e​n​a​d​a​s​.
	 * @param {unknown} n
	 */
	adminManageRegeoSuccess: RequiredParams<'n'>
	/**
	 * N​o​ ​s​e​ ​p​u​d​o​ ​r​e​-​g​e​o​c​o​d​i​f​i​c​a​r
	 */
	adminManageRegeoError: string
	/**
	 * G​e​o​c​o​d​i​f​i​c​a​n​d​o​.​.​.
	 */
	adminManageGeocodingCta: string
	/**
	 * R​e​-​g​e​o​c​o​d​i​f​i​c​a​r
	 */
	adminManageRegeocodeCta: string
	/**
	 * R​e​c​a​r​g​a​r
	 */
	adminManageReloadCta: string
	/**
	 * N​o​ ​h​a​y​ ​p​a​n​o​r​a​m​a​s​ ​e​n​ ​e​s​t​a​ ​c​a​t​e​g​o​r​í​a​.
	 */
	adminManageEmptyCategory: string
	/**
	 * S​i​n​ ​p​r​e​c​i​o
	 */
	adminManageNoPrice: string
	/**
	 * D​i​s​p​o​n​i​b​i​l​i​d​a​d
	 */
	adminManageAvailabilityTitle: string
	/**
	 * D​i​s​p​o​n​i​b​l​e
	 */
	adminManageAvailableLabel: string
	/**
	 * N​o​ ​d​i​s​p​.
	 */
	adminManageUnavailableLabel: string
	/**
	 * V​e​n​c​i​d​o​ ​(​f​e​c​h​a​s​ ​p​a​s​a​d​a​s​)
	 */
	adminManageExpiredLabel: string
	/**
	 * A​g​o​t​a​d​o​ ​(​s​i​n​ ​c​u​p​o​s​)
	 */
	adminManageSoldOutLabel: string
	/**
	 * E​l​i​m​i​n​a​r
	 */
	adminManageDeleteTitle: string
	/**
	 * R​e​e​n​v​i​a​r​ ​c​ó​d​i​g​o
	 */
	otpResendCode: string
	/**
	 * E​l​ ​n​o​m​b​r​e​ ​e​s​ ​o​b​l​i​g​a​t​o​r​i​o​.
	 */
	adminFormErrorNameRequired: string
	/**
	 * E​l​ ​p​r​e​c​i​o​ ​n​o​ ​p​u​e​d​e​ ​s​e​r​ ​n​e​g​a​t​i​v​o​.
	 */
	adminFormErrorPriceNegative: string
	/**
	 * L​o​s​ ​c​u​p​o​s​ ​n​o​ ​p​u​e​d​e​n​ ​s​e​r​ ​n​e​g​a​t​i​v​o​s​.
	 */
	adminFormErrorSlotsNegative: string
	/**
	 * E​l​ ​l​í​m​i​t​e​ ​p​o​r​ ​p​e​r​s​o​n​a​ ​d​e​b​e​ ​s​e​r​ ​m​a​y​o​r​ ​a​ ​0​.
	 */
	adminFormErrorPersonLimitInvalid: string
	/**
	 * E​l​ ​l​í​m​i​t​e​ ​p​o​r​ ​p​e​r​s​o​n​a​ ​n​o​ ​p​u​e​d​e​ ​s​e​r​ ​m​a​y​o​r​ ​q​u​e​ ​l​o​s​ ​c​u​p​o​s​ ​p​o​r​ ​d​í​a​.
	 */
	adminFormErrorPersonLimitExceedsSlots: string
	/**
	 * E​n​ ​l​a​ ​f​e​c​h​a​ ​{​f​e​c​h​a​}​,​ ​l​a​ ​h​o​r​a​ ​d​e​ ​i​n​i​c​i​o​ ​d​e​b​e​ ​s​e​r​ ​a​n​t​e​r​i​o​r​ ​a​ ​l​a​ ​d​e​ ​f​i​n​.
	 * @param {unknown} fecha
	 */
	adminFormErrorTimeRangeInvalid: RequiredParams<'fecha'>
	/**
	 * L​a​ ​f​e​c​h​a​ ​{​f​e​c​h​a​}​ ​y​a​ ​p​a​s​ó​.​ ​E​l​i​g​e​ ​u​n​a​ ​f​e​c​h​a​ ​d​e​ ​h​o​y​ ​e​n​ ​a​d​e​l​a​n​t​e​.
	 * @param {unknown} fecha
	 */
	adminFormErrorPastDate: RequiredParams<'fecha'>
	/**
	 * A​c​t​u​a​l
	 */
	currentUserLabel: string
	/**
	 * D​e​t​a​l​l​e​ ​d​e​l​ ​p​e​d​i​d​o
	 */
	paymentDetailLabel: string
	/**
	 * S​u​b​t​o​t​a​l
	 */
	subtotalLabel: string
	/**
	 * C​a​r​g​o​ ​p​o​r​ ​s​e​r​v​i​c​i​o
	 */
	serviceFeeLabel: string
	/**
	 * T​o​t​a​l
	 */
	totalLabel: string
	/**
	 * V​o​l​v​e​r
	 */
	backLabel: string
	/**
	 * N​o​ ​d​i​s​p​o​n​i​b​l​e
	 */
	soldOutLabel: string
	/**
	 * C​o​n​t​i​n​u​a​r​ ​c​o​n​ ​e​l​ ​p​a​g​o
	 */
	continueToPaymentCta: string
	/**
	 * V​o​l​v​e​r​ ​a​l​ ​d​e​t​a​l​l​e
	 */
	backToDetailLink: string
	/**
	 * ¡​S​o​l​o​ ​q​u​e​d​a​n​ ​{​n​}​ ​c​u​p​o​s​!
	 * @param {unknown} n
	 */
	onlySlotsLeftAlert: RequiredParams<'n'>
	/**
	 * {​n​}​ ​c​u​p​o​s​ ​d​i​s​p​o​n​i​b​l​e​s
	 * @param {unknown} n
	 */
	slotsAvailableAlert: RequiredParams<'n'>
	/**
	 * A​g​o​t​a​d​o​ ​p​a​r​a​ ​e​s​t​a​ ​f​e​c​h​a
	 */
	soldOutForDateAlert: string
	/**
	 * S​i​n​ ​l​í​m​i​t​e​ ​(​3​0​ ​k​m​)
	 */
	radiusMax: string
	/**
	 * A​b​r​i​r​ ​r​a​d​i​o​ ​(​2​0​ ​k​m​)
	 */
	radius20km: string
	/**
	 * A​b​r​i​r​ ​r​a​d​i​o​ ​(​1​0​ ​k​m​)
	 */
	radius10km: string
	/**
	 * A​b​r​i​r​ ​r​a​d​i​o​ ​(​7​ ​k​m​)
	 */
	radius7km: string
	/**
	 * C​e​r​c​a​ ​d​e​ ​m​í​ ​(​5​ ​k​m​)
	 */
	radius5km: string
	/**
	 * C​e​r​c​a​ ​d​e​ ​m​í​ ​(​2​ ​k​m​)
	 */
	radius2km: string
	/**
	 * ✕​ ​Q​u​i​t​a​r​ ​f​e​c​h​a
	 */
	removeDateLink: string
	/**
	 * ↺​ ​R​e​s​t​a​b​l​e​c​e​r​ ​f​i​l​t​r​o​s
	 */
	resetFiltersLink: string
}

export type TranslationFunctions = {
	/**
	 * Cargando...
	 */
	loading: () => LocalizedString
	/**
	 * Cargando panoramas…
	 */
	loadingPanoramas: () => LocalizedString
	/**
	 * Error
	 */
	errorPrefix: () => LocalizedString
	/**
	 * Error de conexión con el servidor
	 */
	serverError: () => LocalizedString
	/**
	 * Iniciar Sesión
	 */
	signIn: () => LocalizedString
	/**
	 * Registrarse
	 */
	register: () => LocalizedString
	/**
	 * Crear Cuenta
	 */
	createAccount: () => LocalizedString
	/**
	 * Continuar con Google
	 */
	continueWithGoogle: () => LocalizedString
	/**
	 * o
	 */
	or: () => LocalizedString
	/**
	 * Autenticación Segura (SSO + OTP)
	 */
	secureAuth: () => LocalizedString
	/**
	 * Nombre
	 */
	name: () => LocalizedString
	/**
	 * Email
	 */
	email: () => LocalizedString
	/**
	 * Contraseña
	 */
	password: () => LocalizedString
	/**
	 * Hubo un problema al conectar con Google.
	 */
	loginGoogleFailed: () => LocalizedString
	/**
	 * Credenciales incorrectas
	 */
	badCredentials: () => LocalizedString
	/**
	 * Error al crear la cuenta
	 */
	createAccountError: () => LocalizedString
	/**
	 * Error crítico en el servidor de registro.
	 */
	registerServerError: () => LocalizedString
	/**
	 * Redirigiendo a Google...
	 */
	redirectingToGoogle: () => LocalizedString
	/**
	 * ¡Sesión iniciada correctamente!
	 */
	loginSuccessToast: () => LocalizedString
	/**
	 * ¡Cuenta creada con éxito! Bienvenido a Panoramas.
	 */
	accountCreatedToast: () => LocalizedString
	/**
	 * Mínimo 8 caracteres
	 */
	pwdMin8: () => LocalizedString
	/**
	 * Al menos 1 mayúscula
	 */
	pwdUppercase: () => LocalizedString
	/**
	 * Al menos 1 número
	 */
	pwdNumber: () => LocalizedString
	/**
	 * Al menos 1 carácter especial
	 */
	pwdSpecial: () => LocalizedString
	/**
	 * Verificación de Seguridad
	 */
	otpTitle: () => LocalizedString
	/**
	 * Ingresa el código de 6 dígitos para confirmar tu identidad.
	 */
	otpInstructions: () => LocalizedString
	/**
	 * Verificar Código
	 */
	otpVerify: () => LocalizedString
	/**
	 * Verificando...
	 */
	otpVerifying: () => LocalizedString
	/**
	 * Código incorrecto o expirado
	 */
	otpInvalid: () => LocalizedString
	/**
	 * Volver al inicio de sesión
	 */
	otpBackToLogin: () => LocalizedString
	/**
	 * Cerrar sesión
	 */
	logout: () => LocalizedString
	/**
	 * Panorama encontrado
	 */
	panoramaFound: () => LocalizedString
	/**
	 * Panoramas encontrados
	 */
	panoramasFound: () => LocalizedString
	/**
	 * No hay actividades publicadas para esta categoría todavía.
	 */
	emptyState: () => LocalizedString
	/**
	 * Filtros
	 */
	filters: () => LocalizedString
	/**
	 * Ver detalles
	 */
	seeDetails: () => LocalizedString
	/**
	 * ☀️ SOLEADO
	 */
	weatherSunny: () => LocalizedString
	/**
	 * ✨ TODO CLIMA
	 */
	weatherAll: () => LocalizedString
	/**
	 * Todas
	 */
	categoryAll: () => LocalizedString
	/**
	 * Cine
	 */
	categoryCine: () => LocalizedString
	/**
	 * Teatro
	 */
	categoryTeatro: () => LocalizedString
	/**
	 * Parque
	 */
	categoryParque: () => LocalizedString
	/**
	 * Museo
	 */
	categoryMuseo: () => LocalizedString
	/**
	 * Restaurante
	 */
	categoryRestaurante: () => LocalizedString
	/**
	 * Miradores
	 */
	categoryMiradores: () => LocalizedString
	/**
	 * Panel de Administrador
	 */
	adminPanel: () => LocalizedString
	/**
	 * ← Volver al inicio
	 */
	adminGoBack: () => LocalizedString
	/**
	 * ADMIN
	 */
	adminBadge: () => LocalizedString
	/**
	 * Admin
	 */
	adminAccessLink: () => LocalizedString
	/**
	 * Activar Admin
	 */
	activateAdminLink: () => LocalizedString
	/**
	 * Mi cuenta
	 */
	myAccountLabel: () => LocalizedString
	/**
	 * Usuarios totales
	 */
	statTotalUsers: () => LocalizedString
	/**
	 * Actividades publicadas
	 */
	statTotalActivities: () => LocalizedString
	/**
	 * OTPs enviados hoy
	 */
	statOtpsSent: () => LocalizedString
	/**
	 * Categoría líder
	 */
	statTopCategory: () => LocalizedString
	/**
	 * Usuarios recientes
	 */
	sectionRecentUsers: () => LocalizedString
	/**
	 * Admins recientes
	 */
	recentAdmins: () => LocalizedString
	/**
	 * Usuarios recientes
	 */
	recentStandardUsers: () => LocalizedString
	/**
	 * Actividades por categoría
	 */
	sectionActivityByCategory: () => LocalizedString
	/**
	 * Email
	 */
	tableEmail: () => LocalizedString
	/**
	 * Rol
	 */
	tableRole: () => LocalizedString
	/**
	 * Registro
	 */
	tableJoined: () => LocalizedString
	/**
	 * Estado
	 */
	tableStatus: () => LocalizedString
	/**
	 * Acción
	 */
	tableAction: () => LocalizedString
	/**
	 * Admin
	 */
	roleAdmin: () => LocalizedString
	/**
	 * Usuario
	 */
	roleUser: () => LocalizedString
	/**
	 * Verificado
	 */
	statusActive: () => LocalizedString
	/**
	 * Pendiente
	 */
	statusPending: () => LocalizedString
	/**
	 * Error al actualizar el rol en la base de datos.
	 */
	roleUpdateError: () => LocalizedString
	/**
	 * Calculando tendencias...
	 */
	calculatingTrend: () => LocalizedString
	/**
	 * Todavía no hay usuarios registrados.
	 */
	adminNoUsersYet: () => LocalizedString
	/**
	 * Todavía no hay panoramas creados.
	 */
	adminNoActivitiesYet: () => LocalizedString
	/**
	 * Dashboard
	 */
	adminTabDashboard: () => LocalizedString
	/**
	 * Crear panorama
	 */
	adminTabCreate: () => LocalizedString
	/**
	 * Administrar panoramas
	 */
	adminTabManage: () => LocalizedString
	/**
	 * Panorama Más Popular (Likes)
	 */
	statPopularActivity: () => LocalizedString
	/**
	 * Evento en Tendencia
	 */
	statTrendingEvent: () => LocalizedString
	/**
	 * Reservar
	 */
	seeDetailsCta: () => LocalizedString
	/**
	 * Confirmar reserva
	 */
	reservationModalTitle: () => LocalizedString
	/**
	 * Vas a reservar este panorama. El pago se procesa al instante.
	 */
	reservationModalDescription: () => LocalizedString
	/**
	 * Confirmar y pagar
	 */
	reservationConfirmPay: () => LocalizedString
	/**
	 * Procesando pago…
	 */
	reservationProcessing: () => LocalizedString
	/**
	 * ¡Reserva confirmada!
	 */
	reservationSuccess: () => LocalizedString
	/**
	 * Podés verla en Mis Reservas.
	 */
	reservationSuccessHint: () => LocalizedString
	/**
	 * No pudimos procesar tu pago.
	 */
	reservationFailed: () => LocalizedString
	/**
	 * Cancelar
	 */
	reservationCancel: () => LocalizedString
	/**
	 * Cerrar
	 */
	reservationClose: () => LocalizedString
	/**
	 * ID Transacción
	 */
	transactionLabel: () => LocalizedString
	/**
	 * Mis Reservas
	 */
	myReservationsLink: () => LocalizedString
	/**
	 * Mis Reservas
	 */
	myReservationsTitle: () => LocalizedString
	/**
	 * Todavía no tenés reservas. Buscá un panorama y reservá.
	 */
	myReservationsEmpty: () => LocalizedString
	/**
	 * Cargando reservas…
	 */
	myReservationsLoading: () => LocalizedString
	/**
	 * Comprado
	 */
	reservationStatusComprado: () => LocalizedString
	/**
	 * Cancelado
	 */
	reservationStatusCancelado: () => LocalizedString
	/**
	 * Pendiente
	 */
	reservationStatusPendiente: () => LocalizedString
	/**
	 * Fecha de reserva
	 */
	reservationDate: () => LocalizedString
	/**
	 * Cancelar reserva
	 */
	reservationCancelAction: () => LocalizedString
	/**
	 * ¿Seguro que querés cancelar esta reserva?
	 */
	reservationCancelConfirm: () => LocalizedString
	/**
	 * Procesando cancelación...
	 */
	reservationCancelProcessing: () => LocalizedString
	/**
	 * Limpiar canceladas
	 */
	reservationClearCancelledCta: () => LocalizedString
	/**
	 * Ver evento
	 */
	viewEventCta: () => LocalizedString
	/**
	 * Reservar
	 */
	reserveOnlyCta: () => LocalizedString
	/**
	 * Cantidad de cupos
	 */
	quantityLabel: () => LocalizedString
	/**
	 * Máximo {n} disponibles
	 */
	quantityMaxHint: (arg: { n: number }) => LocalizedString
	/**
	 * ¿Confirmas tu reserva?
	 */
	confirmReserveTitle: () => LocalizedString
	/**
	 * Vas a reservar {n} cupo(s) para {fecha}.
	 */
	confirmReserveQtyText: (arg: { fecha: string, n: number }) => LocalizedString
	/**
	 * Sí, continuar
	 */
	confirmCta: () => LocalizedString
	/**
	 * No, volver
	 */
	cancelCta: () => LocalizedString
	/**
	 * Generando tu reserva...
	 */
	generatingReservationLabel: () => LocalizedString
	/**
	 * Pagar ahora
	 */
	payNowCta: () => LocalizedString
	/**
	 * Pagar
	 */
	payButton: () => LocalizedString
	/**
	 * Reservar de nuevo
	 */
	rebookCta: () => LocalizedString
	/**
	 * ¡Reserva creada! Pendiente de pago.
	 */
	reservationCreatedPending: () => LocalizedString
	/**
	 * ¡Reserva confirmada y pagada!
	 */
	reservationCreatedPaid: () => LocalizedString
	/**
	 * Detalle del evento
	 */
	detailsModalTitle: () => LocalizedString
	/**
	 * Categoría
	 */
	detailsCategoryLabel: () => LocalizedString
	/**
	 * Clima recomendado
	 */
	detailsWeatherLabel: () => LocalizedString
	/**
	 * Horario
	 */
	detailsHoursLabel: () => LocalizedString
	/**
	 * Ubicación
	 */
	detailsCoordsLabel: () => LocalizedString
	/**
	 * Pagado
	 */
	reservationStatusPagado: () => LocalizedString
	/**
	 * Reservado (pendiente de pago)
	 */
	cardStatusPending: () => LocalizedString
	/**
	 * Comprado
	 */
	cardStatusPaid: () => LocalizedString
	/**
	 * Todas
	 */
	reservationFilterAll: () => LocalizedString
	/**
	 * Activas
	 */
	reservationFilterActive: () => LocalizedString
	/**
	 * Por pagar
	 */
	reservationFilterPending: () => LocalizedString
	/**
	 * Canceladas
	 */
	reservationFilterCancelled: () => LocalizedString
	/**
	 * No hay reservas en esta categoría.
	 */
	reservationFilterEmpty: () => LocalizedString
	/**
	 * Popular
	 */
	badgePopular: () => LocalizedString
	/**
	 * Tendencia
	 */
	badgeTendencia: () => LocalizedString
	/**
	 * Abierto: {open} - {close}
	 */
	openHours: (arg: { close: unknown, open: unknown }) => LocalizedString
	/**
	 * Fecha más próxima: {fecha} · {horarios}
	 */
	nearestDateLabel: (arg: { fecha: string, horarios: string }) => LocalizedString
	/**
	 * 1 horario disponible
	 */
	slotsAvailableSingular: () => LocalizedString
	/**
	 * {n} horarios disponibles
	 */
	slotsAvailableMulti: (arg: { n: number }) => LocalizedString
	/**
	 * Más fechas y horarios: ver evento
	 */
	moreDatesHint: () => LocalizedString
	/**
	 * Afluencia: {level}
	 */
	occupancyLabel: (arg: { level: unknown }) => LocalizedString
	/**
	 * Afluencia ({fecha}): {level}
	 */
	occupancyLabelWithDate: (arg: { fecha: string, level: string }) => LocalizedString
	/**
	 * Cupos disponibles: {disp}/{total}
	 */
	totalSlotsLabel: (arg: { disp: number, total: number }) => LocalizedString
	/**
	 * Alta
	 */
	occupancyHigh: () => LocalizedString
	/**
	 * Media
	 */
	occupancyMedium: () => LocalizedString
	/**
	 * Baja
	 */
	occupancyLow: () => LocalizedString
	/**
	 * Precio base
	 */
	priceLabel: () => LocalizedString
	/**
	 * Gratis
	 */
	free: () => LocalizedString
	/**
	 * No se pudo cargar la disponibilidad.
	 */
	availabilityLoadError: () => LocalizedString
	/**
	 * Clima Sugerido
	 */
	weatherSuggestedLabel: () => LocalizedString
	/**
	 * Ideal Exterior
	 */
	weatherIdealOutdoor: () => LocalizedString
	/**
	 * Apto Todo Clima
	 */
	weatherAllWeatherFit: () => LocalizedString
	/**
	 * Horario
	 */
	scheduleLabel: () => LocalizedString
	/**
	 * + costo de servicio al pagar
	 */
	serviceFeeNote: () => LocalizedString
	/**
	 * Distancia en auto
	 */
	drivingDistanceLabel: () => LocalizedString
	/**
	 * Distancia aproximada
	 */
	straightDistanceLabel: () => LocalizedString
	/**
	 * por carretera
	 */
	byRoad: () => LocalizedString
	/**
	 * en línea recta
	 */
	straightLine: () => LocalizedString
	/**
	 * Dirección
	 */
	addressLabel: () => LocalizedString
	/**
	 * Mapa del Lugar
	 */
	placeMapLabel: () => LocalizedString
	/**
	 * Sin ubicación
	 */
	noLocation: () => LocalizedString
	/**
	 * Elige fecha y horario
	 */
	chooseDateTime: () => LocalizedString
	/**
	 * Cargando disponibilidad...
	 */
	loadingAvailability: () => LocalizedString
	/**
	 * Este panorama no tiene fechas cargadas todavía.
	 */
	noDatesAvailable: () => LocalizedString
	/**
	 * cupos libres
	 */
	slotsFree: () => LocalizedString
	/**
	 * agotado
	 */
	soldOut: () => LocalizedString
	/**
	 * {n} cupos
	 */
	slotsCount: (arg: { n: unknown }) => LocalizedString
	/**
	 * Consultar fecha y hora
	 */
	checkDateTime: () => LocalizedString
	/**
	 * Pagar al tiro
	 */
	payRightNowCta: () => LocalizedString
	/**
	 * Volver al detalle
	 */
	backToDetailCta: () => LocalizedString
	/**
	 * Listo
	 */
	doneCta: () => LocalizedString
	/**
	 * No se pudo reservar
	 */
	reservationFailedGeneric: () => LocalizedString
	/**
	 * ¡Pago realizado! Reserva confirmada y cupo descontado.
	 */
	paymentDoneConfirmed: () => LocalizedString
	/**
	 * Reserva creada (pendiente de pago). Cupo descontado.
	 */
	reservationPendingSpotTaken: () => LocalizedString
	/**
	 * Error al reservar
	 */
	reservationErrorGeneric: () => LocalizedString
	/**
	 * 🧠 ¿No sabes que hacer? Nosotros te Recomendamos !!!
	 */
	recommendBannerTitle: () => LocalizedString
	/**
	 * Encuentra las mejores opciones según el clima y horarios de hoy o de cualquier fecha que elijas.
	 */
	recommendBannerText: () => LocalizedString
	/**
	 * Recomendar Panoramas
	 */
	recommendBannerCta: () => LocalizedString
	/**
	 * 📅 Recomendación para Hoy Activa
	 */
	planningActiveTodayTitle: () => LocalizedString
	/**
	 * 📅 Recomendación Planificada Activa
	 */
	planningActiveFutureTitle: () => LocalizedString
	/**
	 * 📅 Recomendación para los Próximos 5 Días Activa
	 */
	planningActive5DaysTitle: () => LocalizedString
	/**
	 * Mostrando panoramas con cupos disponibles para los próximos 5 días y clima estimado actual.
	 */
	planning5DaysIntro: () => LocalizedString
	/**
	 * Mostrando panoramas ideales para
	 */
	planningTodayIntro: () => LocalizedString
	/**
	 * hoy
	 */
	today: () => LocalizedString
	/**
	 * en tiempo real.
	 */
	inRealTime: () => LocalizedString
	/**
	 * Clima detectado por API:
	 */
	weatherDetectedBy: () => LocalizedString
	/**
	 * Mostrando panoramas para el día
	 */
	planningFutureIntro: () => LocalizedString
	/**
	 * a las
	 */
	atTime: () => LocalizedString
	/**
	 * a cualquier hora
	 */
	anyTimeText: () => LocalizedString
	/**
	 * Clima estimado por API:
	 */
	weatherEstimatedBy: () => LocalizedString
	/**
	 * El clima no se considera para esta fecha (fuera del pronóstico de 5 días).
	 */
	weatherNotConsidered: () => LocalizedString
	/**
	 * ☀️ Despejado
	 */
	weatherClear: () => LocalizedString
	/**
	 * ☁️ Nublado
	 */
	weatherCloudy: () => LocalizedString
	/**
	 * 🌧️ Lluvioso
	 */
	weatherRainy: () => LocalizedString
	/**
	 * 🔄 Volver al Tiempo Real
	 */
	backToRealTimeCta: () => LocalizedString
	/**
	 * Cerca de ti
	 */
	filterNearbyRadius: () => LocalizedString
	/**
	 * Precio: sin orden
	 */
	priceSortNone: () => LocalizedString
	/**
	 * Precio: menor a mayor
	 */
	priceSortAsc: () => LocalizedString
	/**
	 * Precio: mayor a menor
	 */
	priceSortDesc: () => LocalizedString
	/**
	 * Precio: rango personalizado
	 */
	priceSortRange: () => LocalizedString
	/**
	 * Mín $
	 */
	priceMinPlaceholder: () => LocalizedString
	/**
	 * Máx $
	 */
	priceMaxPlaceholder: () => LocalizedString
	/**
	 * Buscando...
	 */
	searching: () => LocalizedString
	/**
	 * Aplicar Filtros
	 */
	applyFilters: () => LocalizedString
	/**
	 * No se pudo conectar con el servicio meteorológico.
	 */
	toastWeatherError: () => LocalizedString
	/**
	 * Eliminado de tus favoritos.
	 */
	toastFavRemoved: () => LocalizedString
	/**
	 * ¡Panorama guardado en tus favoritos!
	 */
	toastFavAdded: () => LocalizedString
	/**
	 * Mostrando {category}.
	 */
	toastShowingCategory: (arg: { category: unknown }) => LocalizedString
	/**
	 * Sesión cerrada correctamente. ¡Vuelve pronto!
	 */
	toastSignoutSuccess: () => LocalizedString
	/**
	 * Hubo un problema al cerrar tu sesión.
	 */
	toastSignoutError: () => LocalizedString
	/**
	 * ¡Reserva completada con éxito!
	 */
	toastReservationSuccess: () => LocalizedString
	/**
	 * Tu sesión ha expirado o es inválida. Por favor, inicia sesión nuevamente.
	 */
	sessionExpiredToast: () => LocalizedString
	/**
	 * Sesión expirada. Por favor, vuelve a ingresar.
	 */
	sessionExpiredRetryToast: () => LocalizedString
	/**
	 * No tienes permisos para realizar esta acción.
	 */
	noPermissionToast: () => LocalizedString
	/**
	 * Selecciona el método para activar Admin:
1. Enviar código automáticamente a mi correo (solo si tu correo está autorizado)
2. Ingresar código manual del Administrador (TOTP)

Ingresa 1 o 2:
	 */
	adminActivatePromptChoice: () => LocalizedString
	/**
	 * Opción inválida. Debes ingresar 1 o 2.
	 */
	adminActivateInvalidChoice: () => LocalizedString
	/**
	 * Solicitando envío de código a tu correo...
	 */
	adminOtpRequestingToast: () => LocalizedString
	/**
	 * No se pudo solicitar el código por correo.
	 */
	adminOtpRequestError: () => LocalizedString
	/**
	 * Código enviado con éxito.
	 */
	adminOtpSentSuccess: () => LocalizedString
	/**
	 * Ingresa el código de 6 dígitos que enviamos a tu correo:
	 */
	adminOtpEnterCodePrompt: () => LocalizedString
	/**
	 * Error de conexión al solicitar el código.
	 */
	adminOtpConnectionError: () => LocalizedString
	/**
	 * Ingresa el código TOTP de 6 dígitos provisto por el Administrador:
	 */
	adminTotpManualPrompt: () => LocalizedString
	/**
	 * Código inválido. Debe ser de 6 dígitos.
	 */
	adminCodeInvalidLength: () => LocalizedString
	/**
	 * correo
	 */
	adminMethodEmail: () => LocalizedString
	/**
	 * TOTP manual
	 */
	adminMethodTotp: () => LocalizedString
	/**
	 * ¡Rol de administrador activado con éxito vía {method}!
	 */
	adminActivateSuccess: (arg: { method: unknown }) => LocalizedString
	/**
	 * Código incorrecto o expirado.
	 */
	adminCodeIncorrectOrExpired: () => LocalizedString
	/**
	 * Error de conexión al activar administrador.
	 */
	adminActivateConnectionError: () => LocalizedString
	/**
	 * Intelligent Assistant
	 */
	planningModalKicker: () => LocalizedString
	/**
	 * Recomendar Panoramas
	 */
	planningModalTitle: () => LocalizedString
	/**
	 * Indica cuándo realizarás la actividad para que el sistema calcule las mejores opciones de forma automática.
	 */
	planningModalDescription: () => LocalizedString
	/**
	 * ¿Cuándo quieres realizar la actividad?
	 */
	whenQuestion: () => LocalizedString
	/**
	 * Hoy
	 */
	todayOptionCta: () => LocalizedString
	/**
	 * Próx. 5 días 📅
	 */
	next5daysOptionCta: () => LocalizedString
	/**
	 * Fecha específica 📅
	 */
	otherDayOptionCta: () => LocalizedString
	/**
	 * Selecciona la fecha
	 */
	selectDateLabel: () => LocalizedString
	/**
	 * ¿A qué hora estimas ir?
	 */
	whatTimeQuestion: () => LocalizedString
	/**
	 * Cualquier hora
	 */
	anyTimeOptionCta: () => LocalizedString
	/**
	 * Hora específica
	 */
	specificTimeOptionCta: () => LocalizedString
	/**
	 * Define la hora específica
	 */
	specificTimeLabel: () => LocalizedString
	/**
	 * Obtener Recomendación
	 */
	getRecommendationCta: () => LocalizedString
	/**
	 * #1 Recomendado
	 */
	rank1Label: () => LocalizedString
	/**
	 * #2 Recomendado
	 */
	rank2Label: () => LocalizedString
	/**
	 * #3 Recomendado
	 */
	rank3Label: () => LocalizedString
	/**
	 * Recomendado
	 */
	recommendedLabel: () => LocalizedString
	/**
	 * Datos del panorama
	 */
	adminFormSectionPanoramaData: () => LocalizedString
	/**
	 * Imagen (URL)
	 */
	adminFormImageLabel: () => LocalizedString
	/**
	 * https://...  URL directa de imagen (.jpg/.png) o blob de Azure
	 */
	adminFormImagePlaceholder: () => LocalizedString
	/**
	 * Se guarda como URL para poder cambiar la imagen en Azure sin tocar el código.
	 */
	adminFormImageHint: () => LocalizedString
	/**
	 * Nombre del panorama
	 */
	adminFormNameLabel: () => LocalizedString
	/**
	 * Ej. Festival de Jazz en el Parque
	 */
	adminFormNamePlaceholder: () => LocalizedString
	/**
	 * Descripción
	 */
	adminFormDescriptionLabel: () => LocalizedString
	/**
	 * Cuenta de qué se trata el panorama...
	 */
	adminFormDescriptionPlaceholder: () => LocalizedString
	/**
	 * Etiqueta de clima
	 */
	adminFormWeatherTagLabel: () => LocalizedString
	/**
	 * Disponible para todo clima
	 */
	adminFormWeatherAllOption: () => LocalizedString
	/**
	 * Solo días despejados
	 */
	adminFormWeatherSunnyOption: () => LocalizedString
	/**
	 * Dirección o localidad real
	 */
	adminFormAddressLabel: () => LocalizedString
	/**
	 * Ej. Av. Kennedy 5413, Las Condes, Santiago
	 */
	adminFormAddressPlaceholder: () => LocalizedString
	/**
	 * Desde esta dirección, el backend obtendrá las <strong>coordenadas (lat/lng)</strong> mediante geocodificación con Google. Con esas coordenadas y la ubicación del usuario, la app calcula la <strong>distancia aproximada</strong>, que se muestra en la tarjeta del panorama (no se ingresa aquí).
	 */
	adminFormGeoInfoHtml: () => LocalizedString
	/**
	 * → Ver dónde aparece en la vista previa de la derecha.
	 */
	adminFormGeoInfoHint: () => LocalizedString
	/**
	 * ✓ Ubicación seleccionada de Google (coordenadas capturadas).
	 */
	adminFormLocationSelected: () => LocalizedString
	/**
	 * Horarios y fechas
	 */
	adminFormSchedulesSection: () => LocalizedString
	/**
	 * Agregar fecha
	 */
	adminFormAddDateCta: () => LocalizedString
	/**
	 * Fecha
	 */
	adminFormDateLabel: () => LocalizedString
	/**
	 * Quitar fecha
	 */
	adminFormRemoveDateTitle: () => LocalizedString
	/**
	 * Inicio
	 */
	adminFormStartLabel: () => LocalizedString
	/**
	 * Fin
	 */
	adminFormEndLabel: () => LocalizedString
	/**
	 * Quitar horario
	 */
	adminFormRemoveSlotTitle: () => LocalizedString
	/**
	 * Agregar horario a esta fecha
	 */
	adminFormAddSlotCta: () => LocalizedString
	/**
	 * Precio y disponibilidad
	 */
	adminFormPriceSection: () => LocalizedString
	/**
	 * Precio (CLP)
	 */
	adminFormPriceLabel: () => LocalizedString
	/**
	 * 0 = gratis
	 */
	adminFormPricePlaceholder: () => LocalizedString
	/**
	 * Cupos por día
	 */
	adminFormSlotsLabel: () => LocalizedString
	/**
	 * Ej. 50
	 */
	adminFormSlotsPlaceholder: () => LocalizedString
	/**
	 * Cupos que entrega el convenio cada día. Se descuentan con cada reserva/compra y se reinician al día siguiente.
	 */
	adminFormSlotsHint: () => LocalizedString
	/**
	 * Límite por persona
	 */
	adminFormPersonLimitLabel: () => LocalizedString
	/**
	 * Sin límite
	 */
	adminFormPersonLimitPlaceholder: () => LocalizedString
	/**
	 * Máximo de cupos que una misma persona puede reservar en un mismo horario. Vacío = sin límite.
	 */
	adminFormPersonLimitHint: () => LocalizedString
	/**
	 * Guardando...
	 */
	adminFormSavingCta: () => LocalizedString
	/**
	 * Crear panorama
	 */
	adminFormSubmitCta: () => LocalizedString
	/**
	 * Datos que se enviarán al backend (próxima etapa)
	 */
	adminFormPreviewPayloadTitle: () => LocalizedString
	/**
	 * Vista previa
	 */
	adminFormPreviewLabel: () => LocalizedString
	/**
	 * Despejado
	 */
	adminWeatherSunnyShort: () => LocalizedString
	/**
	 * Todo clima
	 */
	adminWeatherAllShort: () => LocalizedString
	/**
	 * por definir
	 */
	adminFormScheduleTBD: () => LocalizedString
	/**
	 * Detalle (al tocar "Ver evento")
	 */
	adminFormDetailPreviewLabel: () => LocalizedString
	/**
	 * Aquí aparecerá la descripción que escribas.
	 */
	adminFormDescriptionFallback: () => LocalizedString
	/**
	 * Sin dirección
	 */
	adminFormNoAddressValue: () => LocalizedString
	/**
	 * Aquí se mostrará el mapa de Google del lugar
	 */
	adminFormMapPlaceholderText: () => LocalizedString
	/**
	 * El badge ~2,4 km es donde se mostrará la distancia real al usuario (calculada desde la dirección geocodificada). El número es de ejemplo hasta conectar la geocodificación.
	 */
	adminFormDistanceNote: () => LocalizedString
	/**
	 * Error al crear el panorama
	 */
	adminFormErrorCreating: () => LocalizedString
	/**
	 * Panorama creado y guardado. Dirección geocodificada.
	 */
	adminFormSuccessGeocoded: () => LocalizedString
	/**
	 * Panorama creado y guardado (la dirección no se pudo geocodificar; sin distancia por ahora).
	 */
	adminFormSuccessNotGeocoded: () => LocalizedString
	/**
	 * No se pudo guardar el panorama.
	 */
	adminFormSaveErrorGeneric: () => LocalizedString
	/**
	 * No se pudieron cargar los panoramas
	 */
	adminManageLoadError: () => LocalizedString
	/**
	 * Error al cargar
	 */
	adminManageLoadErrorGeneric: () => LocalizedString
	/**
	 * ¿Eliminar "{name}"? Esta acción no se puede deshacer.
	 */
	adminManageDeleteConfirm: (arg: { name: unknown }) => LocalizedString
	/**
	 * {n} panorama(s) actualizados con coordenadas.
	 */
	adminManageRegeoSuccess: (arg: { n: unknown }) => LocalizedString
	/**
	 * No se pudo re-geocodificar
	 */
	adminManageRegeoError: () => LocalizedString
	/**
	 * Geocodificando...
	 */
	adminManageGeocodingCta: () => LocalizedString
	/**
	 * Re-geocodificar
	 */
	adminManageRegeocodeCta: () => LocalizedString
	/**
	 * Recargar
	 */
	adminManageReloadCta: () => LocalizedString
	/**
	 * No hay panoramas en esta categoría.
	 */
	adminManageEmptyCategory: () => LocalizedString
	/**
	 * Sin precio
	 */
	adminManageNoPrice: () => LocalizedString
	/**
	 * Disponibilidad
	 */
	adminManageAvailabilityTitle: () => LocalizedString
	/**
	 * Disponible
	 */
	adminManageAvailableLabel: () => LocalizedString
	/**
	 * No disp.
	 */
	adminManageUnavailableLabel: () => LocalizedString
	/**
	 * Vencido (fechas pasadas)
	 */
	adminManageExpiredLabel: () => LocalizedString
	/**
	 * Agotado (sin cupos)
	 */
	adminManageSoldOutLabel: () => LocalizedString
	/**
	 * Eliminar
	 */
	adminManageDeleteTitle: () => LocalizedString
	/**
	 * Reenviar código
	 */
	otpResendCode: () => LocalizedString
	/**
	 * El nombre es obligatorio.
	 */
	adminFormErrorNameRequired: () => LocalizedString
	/**
	 * El precio no puede ser negativo.
	 */
	adminFormErrorPriceNegative: () => LocalizedString
	/**
	 * Los cupos no pueden ser negativos.
	 */
	adminFormErrorSlotsNegative: () => LocalizedString
	/**
	 * El límite por persona debe ser mayor a 0.
	 */
	adminFormErrorPersonLimitInvalid: () => LocalizedString
	/**
	 * El límite por persona no puede ser mayor que los cupos por día.
	 */
	adminFormErrorPersonLimitExceedsSlots: () => LocalizedString
	/**
	 * En la fecha {fecha}, la hora de inicio debe ser anterior a la de fin.
	 */
	adminFormErrorTimeRangeInvalid: (arg: { fecha: unknown }) => LocalizedString
	/**
	 * La fecha {fecha} ya pasó. Elige una fecha de hoy en adelante.
	 */
	adminFormErrorPastDate: (arg: { fecha: unknown }) => LocalizedString
	/**
	 * Actual
	 */
	currentUserLabel: () => LocalizedString
	/**
	 * Detalle del pedido
	 */
	paymentDetailLabel: () => LocalizedString
	/**
	 * Subtotal
	 */
	subtotalLabel: () => LocalizedString
	/**
	 * Cargo por servicio
	 */
	serviceFeeLabel: () => LocalizedString
	/**
	 * Total
	 */
	totalLabel: () => LocalizedString
	/**
	 * Volver
	 */
	backLabel: () => LocalizedString
	/**
	 * No disponible
	 */
	soldOutLabel: () => LocalizedString
	/**
	 * Continuar con el pago
	 */
	continueToPaymentCta: () => LocalizedString
	/**
	 * Volver al detalle
	 */
	backToDetailLink: () => LocalizedString
	/**
	 * ¡Solo quedan {n} cupos!
	 */
	onlySlotsLeftAlert: (arg: { n: unknown }) => LocalizedString
	/**
	 * {n} cupos disponibles
	 */
	slotsAvailableAlert: (arg: { n: unknown }) => LocalizedString
	/**
	 * Agotado para esta fecha
	 */
	soldOutForDateAlert: () => LocalizedString
	/**
	 * Sin límite (30 km)
	 */
	radiusMax: () => LocalizedString
	/**
	 * Abrir radio (20 km)
	 */
	radius20km: () => LocalizedString
	/**
	 * Abrir radio (10 km)
	 */
	radius10km: () => LocalizedString
	/**
	 * Abrir radio (7 km)
	 */
	radius7km: () => LocalizedString
	/**
	 * Cerca de mí (5 km)
	 */
	radius5km: () => LocalizedString
	/**
	 * Cerca de mí (2 km)
	 */
	radius2km: () => LocalizedString
	/**
	 * ✕ Quitar fecha
	 */
	removeDateLink: () => LocalizedString
	/**
	 * ↺ Restablecer filtros
	 */
	resetFiltersLink: () => LocalizedString
}

export type Formatters = {}
