// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'es'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * C​a​r​g​a​n​d​o​.​.​.
	 */
	loading: string
	/**
	 * C​a​r​g​a​n​d​o​ ​p​a​n​o​r​a​m​a​s​…
	 */
	loadingPanoramas: string
	/**
	 * E​r​r​o​r
	 */
	errorPrefix: string
	/**
	 * E​r​r​o​r​ ​d​e​ ​c​o​n​e​x​i​ó​n​ ​c​o​n​ ​e​l​ ​s​e​r​v​i​d​o​r
	 */
	serverError: string
	/**
	 * I​n​i​c​i​a​r​ ​S​e​s​i​ó​n
	 */
	signIn: string
	/**
	 * R​e​g​i​s​t​r​a​r​s​e
	 */
	register: string
	/**
	 * C​r​e​a​r​ ​C​u​e​n​t​a
	 */
	createAccount: string
	/**
	 * C​o​n​t​i​n​u​a​r​ ​c​o​n​ ​G​o​o​g​l​e
	 */
	continueWithGoogle: string
	/**
	 * o
	 */
	or: string
	/**
	 * A​u​t​e​n​t​i​c​a​c​i​ó​n​ ​S​e​g​u​r​a​ ​(​S​S​O​ ​+​ ​O​T​P​)
	 */
	secureAuth: string
	/**
	 * N​o​m​b​r​e
	 */
	name: string
	/**
	 * E​m​a​i​l
	 */
	email: string
	/**
	 * C​o​n​t​r​a​s​e​ñ​a
	 */
	password: string
	/**
	 * H​u​b​o​ ​u​n​ ​p​r​o​b​l​e​m​a​ ​a​l​ ​c​o​n​e​c​t​a​r​ ​c​o​n​ ​G​o​o​g​l​e​.
	 */
	loginGoogleFailed: string
	/**
	 * C​r​e​d​e​n​c​i​a​l​e​s​ ​i​n​c​o​r​r​e​c​t​a​s
	 */
	badCredentials: string
	/**
	 * E​r​r​o​r​ ​a​l​ ​c​r​e​a​r​ ​l​a​ ​c​u​e​n​t​a
	 */
	createAccountError: string
	/**
	 * M​í​n​i​m​o​ ​8​ ​c​a​r​a​c​t​e​r​e​s
	 */
	pwdMin8: string
	/**
	 * A​l​ ​m​e​n​o​s​ ​1​ ​m​a​y​ú​s​c​u​l​a
	 */
	pwdUppercase: string
	/**
	 * A​l​ ​m​e​n​o​s​ ​1​ ​n​ú​m​e​r​o
	 */
	pwdNumber: string
	/**
	 * A​l​ ​m​e​n​o​s​ ​1​ ​c​a​r​á​c​t​e​r​ ​e​s​p​e​c​i​a​l
	 */
	pwdSpecial: string
	/**
	 * V​e​r​i​f​i​c​a​c​i​ó​n​ ​d​e​ ​S​e​g​u​r​i​d​a​d
	 */
	otpTitle: string
	/**
	 * I​n​g​r​e​s​a​ ​e​l​ ​c​ó​d​i​g​o​ ​d​e​ ​6​ ​d​í​g​i​t​o​s​ ​p​a​r​a​ ​c​o​n​f​i​r​m​a​r​ ​t​u​ ​i​d​e​n​t​i​d​a​d​.
	 */
	otpInstructions: string
	/**
	 * V​e​r​i​f​i​c​a​r​ ​C​ó​d​i​g​o
	 */
	otpVerify: string
	/**
	 * V​e​r​i​f​i​c​a​n​d​o​.​.​.
	 */
	otpVerifying: string
	/**
	 * C​ó​d​i​g​o​ ​i​n​c​o​r​r​e​c​t​o​ ​o​ ​e​x​p​i​r​a​d​o
	 */
	otpInvalid: string
	/**
	 * V​o​l​v​e​r​ ​a​l​ ​i​n​i​c​i​o​ ​d​e​ ​s​e​s​i​ó​n
	 */
	otpBackToLogin: string
	/**
	 * C​e​r​r​a​r​ ​s​e​s​i​ó​n
	 */
	logout: string
	/**
	 * P​a​n​o​r​a​m​a​ ​e​n​c​o​n​t​r​a​d​o
	 */
	panoramaFound: string
	/**
	 * P​a​n​o​r​a​m​a​s​ ​e​n​c​o​n​t​r​a​d​o​s
	 */
	panoramasFound: string
	/**
	 * N​o​ ​h​a​y​ ​a​c​t​i​v​i​d​a​d​e​s​ ​p​u​b​l​i​c​a​d​a​s​ ​p​a​r​a​ ​e​s​t​a​ ​c​a​t​e​g​o​r​í​a​ ​t​o​d​a​v​í​a​.
	 */
	emptyState: string
	/**
	 * F​i​l​t​r​o​s
	 */
	filters: string
	/**
	 * V​e​r​ ​d​e​t​a​l​l​e​s
	 */
	seeDetails: string
	/**
	 * ☀​️​ ​S​O​L​E​A​D​O
	 */
	weatherSunny: string
	/**
	 * ✨​ ​T​O​D​O​ ​C​L​I​M​A
	 */
	weatherAll: string
	/**
	 * T​o​d​a​s
	 */
	categoryAll: string
	/**
	 * C​i​n​e
	 */
	categoryCine: string
	/**
	 * T​e​a​t​r​o
	 */
	categoryTeatro: string
	/**
	 * P​a​r​q​u​e
	 */
	categoryParque: string
	/**
	 * M​u​s​e​o
	 */
	categoryMuseo: string
	/**
	 * R​e​s​t​a​u​r​a​n​t​e
	 */
	categoryRestaurante: string
	/**
	 * M​i​r​a​d​o​r​e​s
	 */
	categoryMiradores: string
	/**
	 * P​a​n​e​l​ ​d​e​ ​A​d​m​i​n​i​s​t​r​a​d​o​r
	 */
	adminPanel: string
	/**
	 * ←​ ​V​o​l​v​e​r​ ​a​l​ ​i​n​i​c​i​o
	 */
	adminGoBack: string
	/**
	 * A​D​M​I​N
	 */
	adminBadge: string
	/**
	 * A​d​m​i​n
	 */
	adminAccessLink: string
	/**
	 * U​s​u​a​r​i​o​s​ ​t​o​t​a​l​e​s
	 */
	statTotalUsers: string
	/**
	 * A​c​t​i​v​i​d​a​d​e​s​ ​p​u​b​l​i​c​a​d​a​s
	 */
	statTotalActivities: string
	/**
	 * O​T​P​s​ ​e​n​v​i​a​d​o​s​ ​h​o​y
	 */
	statOtpsSent: string
	/**
	 * C​a​t​e​g​o​r​í​a​ ​l​í​d​e​r
	 */
	statTopCategory: string
	/**
	 * U​s​u​a​r​i​o​s​ ​r​e​c​i​e​n​t​e​s
	 */
	sectionRecentUsers: string
	/**
	 * A​d​m​i​n​s​ ​r​e​c​i​e​n​t​e​s
	 */
	recentAdmins: string
	/**
	 * U​s​u​a​r​i​o​s​ ​r​e​c​i​e​n​t​e​s
	 */
	recentStandardUsers: string
	/**
	 * A​c​t​i​v​i​d​a​d​e​s​ ​p​o​r​ ​c​a​t​e​g​o​r​í​a
	 */
	sectionActivityByCategory: string
	/**
	 * E​m​a​i​l
	 */
	tableEmail: string
	/**
	 * R​o​l
	 */
	tableRole: string
	/**
	 * R​e​g​i​s​t​r​o
	 */
	tableJoined: string
	/**
	 * E​s​t​a​d​o
	 */
	tableStatus: string
	/**
	 * A​d​m​i​n
	 */
	roleAdmin: string
	/**
	 * U​s​u​a​r​i​o
	 */
	roleUser: string
	/**
	 * V​e​r​i​f​i​c​a​d​o
	 */
	statusActive: string
	/**
	 * P​e​n​d​i​e​n​t​e
	 */
	statusPending: string
	/**
	 * E​r​r​o​r​ ​a​l​ ​a​c​t​u​a​l​i​z​a​r​ ​e​l​ ​r​o​l​ ​e​n​ ​l​a​ ​b​a​s​e​ ​d​e​ ​d​a​t​o​s​.
	 */
	roleUpdateError: string
	/**
	 * C​a​l​c​u​l​a​n​d​o​ ​t​e​n​d​e​n​c​i​a​s​.​.​.
	 */
	calculatingTrend: string
	/**
	 * R​e​s​e​r​v​a​r
	 */
	seeDetailsCta: string
	/**
	 * C​o​n​f​i​r​m​a​r​ ​r​e​s​e​r​v​a
	 */
	reservationModalTitle: string
	/**
	 * V​a​s​ ​a​ ​r​e​s​e​r​v​a​r​ ​e​s​t​e​ ​p​a​n​o​r​a​m​a​.​ ​E​l​ ​p​a​g​o​ ​s​e​ ​p​r​o​c​e​s​a​ ​a​l​ ​i​n​s​t​a​n​t​e​.
	 */
	reservationModalDescription: string
	/**
	 * C​o​n​f​i​r​m​a​r​ ​y​ ​p​a​g​a​r
	 */
	reservationConfirmPay: string
	/**
	 * P​r​o​c​e​s​a​n​d​o​ ​p​a​g​o​…
	 */
	reservationProcessing: string
	/**
	 * ¡​R​e​s​e​r​v​a​ ​c​o​n​f​i​r​m​a​d​a​!
	 */
	reservationSuccess: string
	/**
	 * P​o​d​é​s​ ​v​e​r​l​a​ ​e​n​ ​M​i​s​ ​R​e​s​e​r​v​a​s​.
	 */
	reservationSuccessHint: string
	/**
	 * N​o​ ​p​u​d​i​m​o​s​ ​p​r​o​c​e​s​a​r​ ​t​u​ ​p​a​g​o​.
	 */
	reservationFailed: string
	/**
	 * C​a​n​c​e​l​a​r
	 */
	reservationCancel: string
	/**
	 * C​e​r​r​a​r
	 */
	reservationClose: string
	/**
	 * I​D​ ​T​r​a​n​s​a​c​c​i​ó​n
	 */
	transactionLabel: string
	/**
	 * M​i​s​ ​R​e​s​e​r​v​a​s
	 */
	myReservationsLink: string
	/**
	 * M​i​s​ ​R​e​s​e​r​v​a​s
	 */
	myReservationsTitle: string
	/**
	 * T​o​d​a​v​í​a​ ​n​o​ ​t​e​n​é​s​ ​r​e​s​e​r​v​a​s​.​ ​B​u​s​c​á​ ​u​n​ ​p​a​n​o​r​a​m​a​ ​y​ ​r​e​s​e​r​v​á​.
	 */
	myReservationsEmpty: string
	/**
	 * C​a​r​g​a​n​d​o​ ​r​e​s​e​r​v​a​s​…
	 */
	myReservationsLoading: string
	/**
	 * C​o​m​p​r​a​d​o
	 */
	reservationStatusComprado: string
	/**
	 * C​a​n​c​e​l​a​d​o
	 */
	reservationStatusCancelado: string
	/**
	 * P​e​n​d​i​e​n​t​e
	 */
	reservationStatusPendiente: string
	/**
	 * F​e​c​h​a​ ​d​e​ ​r​e​s​e​r​v​a
	 */
	reservationDate: string
	/**
	 * C​a​n​c​e​l​a​r​ ​r​e​s​e​r​v​a
	 */
	reservationCancelAction: string
	/**
	 * ¿​S​e​g​u​r​o​ ​q​u​e​ ​q​u​e​r​é​s​ ​c​a​n​c​e​l​a​r​ ​e​s​t​a​ ​r​e​s​e​r​v​a​?
	 */
	reservationCancelConfirm: string
	/**
	 * V​e​r​ ​e​v​e​n​t​o
	 */
	viewEventCta: string
	/**
	 * R​e​s​e​r​v​a​r
	 */
	reserveOnlyCta: string
	/**
	 * P​a​g​a​r​ ​a​h​o​r​a
	 */
	payNowCta: string
	/**
	 * P​a​g​a​r
	 */
	payButton: string
	/**
	 * R​e​s​e​r​v​a​r​ ​d​e​ ​n​u​e​v​o
	 */
	rebookCta: string
	/**
	 * ¡​R​e​s​e​r​v​a​ ​c​r​e​a​d​a​!​ ​P​e​n​d​i​e​n​t​e​ ​d​e​ ​p​a​g​o​.
	 */
	reservationCreatedPending: string
	/**
	 * ¡​R​e​s​e​r​v​a​ ​c​o​n​f​i​r​m​a​d​a​ ​y​ ​p​a​g​a​d​a​!
	 */
	reservationCreatedPaid: string
	/**
	 * D​e​t​a​l​l​e​ ​d​e​l​ ​e​v​e​n​t​o
	 */
	detailsModalTitle: string
	/**
	 * C​a​t​e​g​o​r​í​a
	 */
	detailsCategoryLabel: string
	/**
	 * C​l​i​m​a​ ​r​e​c​o​m​e​n​d​a​d​o
	 */
	detailsWeatherLabel: string
	/**
	 * H​o​r​a​r​i​o
	 */
	detailsHoursLabel: string
	/**
	 * U​b​i​c​a​c​i​ó​n
	 */
	detailsCoordsLabel: string
	/**
	 * P​a​g​a​d​o
	 */
	reservationStatusPagado: string
	/**
	 * R​e​s​e​r​v​a​d​o​ ​(​p​e​n​d​i​e​n​t​e​ ​d​e​ ​p​a​g​o​)
	 */
	cardStatusPending: string
	/**
	 * C​o​m​p​r​a​d​o
	 */
	cardStatusPaid: string
	/**
	 * P​o​p​u​l​a​r
	 */
	badgePopular: string
	/**
	 * T​e​n​d​e​n​c​i​a
	 */
	badgeTendencia: string
	/**
	 * A​b​i​e​r​t​o​:​ ​{​o​p​e​n​}​ ​-​ ​{​c​l​o​s​e​}
	 * @param {unknown} close
	 * @param {unknown} open
	 */
	openHours: RequiredParams<'close' | 'open'>
	/**
	 * A​f​l​u​e​n​c​i​a​:​ ​{​l​e​v​e​l​}
	 * @param {unknown} level
	 */
	occupancyLabel: RequiredParams<'level'>
	/**
	 * A​l​t​a
	 */
	occupancyHigh: string
	/**
	 * M​e​d​i​a
	 */
	occupancyMedium: string
	/**
	 * B​a​j​a
	 */
	occupancyLow: string
	/**
	 * P​r​e​c​i​o​ ​b​a​s​e
	 */
	priceLabel: string
	/**
	 * G​r​a​t​i​s
	 */
	free: string
	/**
	 * N​o​ ​s​e​ ​p​u​d​o​ ​c​a​r​g​a​r​ ​l​a​ ​d​i​s​p​o​n​i​b​i​l​i​d​a​d​.
	 */
	availabilityLoadError: string
	/**
	 * C​l​i​m​a​ ​S​u​g​e​r​i​d​o
	 */
	weatherSuggestedLabel: string
	/**
	 * I​d​e​a​l​ ​E​x​t​e​r​i​o​r
	 */
	weatherIdealOutdoor: string
	/**
	 * A​p​t​o​ ​T​o​d​o​ ​C​l​i​m​a
	 */
	weatherAllWeatherFit: string
	/**
	 * H​o​r​a​r​i​o
	 */
	scheduleLabel: string
	/**
	 * +​ ​c​o​s​t​o​ ​d​e​ ​s​e​r​v​i​c​i​o​ ​a​l​ ​p​a​g​a​r
	 */
	serviceFeeNote: string
	/**
	 * D​i​s​t​a​n​c​i​a​ ​e​n​ ​a​u​t​o
	 */
	drivingDistanceLabel: string
	/**
	 * D​i​s​t​a​n​c​i​a​ ​a​p​r​o​x​i​m​a​d​a
	 */
	straightDistanceLabel: string
	/**
	 * p​o​r​ ​c​a​r​r​e​t​e​r​a
	 */
	byRoad: string
	/**
	 * e​n​ ​l​í​n​e​a​ ​r​e​c​t​a
	 */
	straightLine: string
	/**
	 * D​i​r​e​c​c​i​ó​n
	 */
	addressLabel: string
	/**
	 * M​a​p​a​ ​d​e​l​ ​L​u​g​a​r
	 */
	placeMapLabel: string
	/**
	 * S​i​n​ ​u​b​i​c​a​c​i​ó​n
	 */
	noLocation: string
	/**
	 * E​l​i​g​e​ ​f​e​c​h​a​ ​y​ ​h​o​r​a​r​i​o
	 */
	chooseDateTime: string
	/**
	 * C​a​r​g​a​n​d​o​ ​d​i​s​p​o​n​i​b​i​l​i​d​a​d​.​.​.
	 */
	loadingAvailability: string
	/**
	 * E​s​t​e​ ​p​a​n​o​r​a​m​a​ ​n​o​ ​t​i​e​n​e​ ​f​e​c​h​a​s​ ​c​a​r​g​a​d​a​s​ ​t​o​d​a​v​í​a​.
	 */
	noDatesAvailable: string
	/**
	 * c​u​p​o​s​ ​l​i​b​r​e​s
	 */
	slotsFree: string
	/**
	 * a​g​o​t​a​d​o
	 */
	soldOut: string
	/**
	 * {​n​}​ ​c​u​p​o​s
	 * @param {unknown} n
	 */
	slotsCount: RequiredParams<'n'>
	/**
	 * C​o​n​s​u​l​t​a​r​ ​f​e​c​h​a​ ​y​ ​h​o​r​a
	 */
	checkDateTime: string
	/**
	 * P​a​g​a​r​ ​a​l​ ​t​i​r​o
	 */
	payRightNowCta: string
	/**
	 * V​o​l​v​e​r​ ​a​l​ ​d​e​t​a​l​l​e
	 */
	backToDetailCta: string
	/**
	 * L​i​s​t​o
	 */
	doneCta: string
	/**
	 * N​o​ ​s​e​ ​p​u​d​o​ ​r​e​s​e​r​v​a​r
	 */
	reservationFailedGeneric: string
	/**
	 * ¡​P​a​g​o​ ​r​e​a​l​i​z​a​d​o​!​ ​R​e​s​e​r​v​a​ ​c​o​n​f​i​r​m​a​d​a​ ​y​ ​c​u​p​o​ ​d​e​s​c​o​n​t​a​d​o​.
	 */
	paymentDoneConfirmed: string
	/**
	 * R​e​s​e​r​v​a​ ​c​r​e​a​d​a​ ​(​p​e​n​d​i​e​n​t​e​ ​d​e​ ​p​a​g​o​)​.​ ​C​u​p​o​ ​d​e​s​c​o​n​t​a​d​o​.
	 */
	reservationPendingSpotTaken: string
	/**
	 * E​r​r​o​r​ ​a​l​ ​r​e​s​e​r​v​a​r
	 */
	reservationErrorGeneric: string
	/**
	 * �​�​ ​¿​Q​u​i​e​r​e​s​ ​r​e​c​o​m​e​n​d​a​c​i​o​n​e​s​ ​p​e​r​s​o​n​a​l​i​z​a​d​a​s​ ​d​e​ ​p​a​n​o​r​a​m​a​s​?
	 */
	recommendBannerTitle: string
	/**
	 * E​n​c​u​e​n​t​r​a​ ​l​a​s​ ​m​e​j​o​r​e​s​ ​o​p​c​i​o​n​e​s​ ​s​e​g​ú​n​ ​e​l​ ​c​l​i​m​a​ ​y​ ​h​o​r​a​r​i​o​s​ ​d​e​ ​h​o​y​ ​o​ ​d​e​ ​c​u​a​l​q​u​i​e​r​ ​f​e​c​h​a​ ​q​u​e​ ​e​l​i​j​a​s​.
	 */
	recommendBannerText: string
	/**
	 * ✨​ ​R​e​c​o​m​e​n​d​a​r​ ​P​a​n​o​r​a​m​a​s
	 */
	recommendBannerCta: string
	/**
	 * �​�​ ​R​e​c​o​m​e​n​d​a​c​i​ó​n​ ​p​a​r​a​ ​H​o​y​ ​A​c​t​i​v​a
	 */
	planningActiveTodayTitle: string
	/**
	 * �​�​ ​R​e​c​o​m​e​n​d​a​c​i​ó​n​ ​P​l​a​n​i​f​i​c​a​d​a​ ​A​c​t​i​v​a
	 */
	planningActiveFutureTitle: string
	/**
	 * M​o​s​t​r​a​n​d​o​ ​p​a​n​o​r​a​m​a​s​ ​i​d​e​a​l​e​s​ ​p​a​r​a
	 */
	planningTodayIntro: string
	/**
	 * h​o​y
	 */
	today: string
	/**
	 * e​n​ ​t​i​e​m​p​o​ ​r​e​a​l​.
	 */
	inRealTime: string
	/**
	 * C​l​i​m​a​ ​d​e​t​e​c​t​a​d​o​ ​p​o​r​ ​A​P​I​:
	 */
	weatherDetectedBy: string
	/**
	 * M​o​s​t​r​a​n​d​o​ ​p​a​n​o​r​a​m​a​s​ ​p​a​r​a​ ​e​l​ ​d​í​a
	 */
	planningFutureIntro: string
	/**
	 * a​ ​l​a​s
	 */
	atTime: string
	/**
	 * a​ ​c​u​a​l​q​u​i​e​r​ ​h​o​r​a
	 */
	anyTimeText: string
	/**
	 * C​l​i​m​a​ ​e​s​t​i​m​a​d​o​ ​p​o​r​ ​A​P​I​:
	 */
	weatherEstimatedBy: string
	/**
	 * ☀​️​ ​D​e​s​p​e​j​a​d​o
	 */
	weatherClear: string
	/**
	 * ☁​️​ ​N​u​b​l​a​d​o
	 */
	weatherCloudy: string
	/**
	 * �​�​️​ ​L​l​u​v​i​o​s​o
	 */
	weatherRainy: string
	/**
	 * �​�​ ​V​o​l​v​e​r​ ​a​l​ ​T​i​e​m​p​o​ ​R​e​a​l
	 */
	backToRealTimeCta: string
	/**
	 * T​o​d​a​ ​l​a​ ​r​e​g​i​ó​n
	 */
	filterRadiusAll: string
	/**
	 * A​ ​m​e​n​o​s​ ​d​e​ ​1​0​k​m
	 */
	filterRadius10: string
	/**
	 * A​ ​m​e​n​o​s​ ​d​e​ ​5​k​m
	 */
	filterRadius5: string
	/**
	 * A​ ​m​e​n​o​s​ ​d​e​ ​2​k​m
	 */
	filterRadius2: string
	/**
	 * C​u​a​l​q​u​i​e​r​ ​p​r​e​c​i​o
	 */
	filterAnyPrice: string
	/**
	 * E​c​o​n​ó​m​i​c​o​ ​(​$​)
	 */
	filterPriceCheap: string
	/**
	 * M​o​d​e​r​a​d​o​ ​(​$​$​)
	 */
	filterPriceModerate: string
	/**
	 * C​o​s​t​o​s​o​ ​(​$​$​$​)
	 */
	filterPriceExpensive: string
	/**
	 * M​u​y​ ​C​o​s​t​o​s​o​ ​(​$​$​$​$​)
	 */
	filterPriceVeryExpensive: string
	/**
	 * G​r​a​t​i​s​ ​(​$​0​)
	 */
	filterFreePrice: string
	/**
	 * D​e​ ​p​a​g​o
	 */
	filterPaidPrice: string
	/**
	 * S​o​l​o​ ​A​b​i​e​r​t​o​s​ ​A​h​o​r​a
	 */
	filterOpenNow: string
	/**
	 * B​u​s​c​a​n​d​o​.​.​.
	 */
	searching: string
	/**
	 * A​p​l​i​c​a​r​ ​F​i​l​t​r​o​s
	 */
	applyFilters: string
	/**
	 * N​o​ ​s​e​ ​p​u​d​o​ ​c​o​n​e​c​t​a​r​ ​c​o​n​ ​e​l​ ​s​e​r​v​i​c​i​o​ ​m​e​t​e​o​r​o​l​ó​g​i​c​o​.
	 */
	toastWeatherError: string
	/**
	 * E​l​i​m​i​n​a​d​o​ ​d​e​ ​t​u​s​ ​f​a​v​o​r​i​t​o​s​.
	 */
	toastFavRemoved: string
	/**
	 * ¡​P​a​n​o​r​a​m​a​ ​g​u​a​r​d​a​d​o​ ​e​n​ ​t​u​s​ ​f​a​v​o​r​i​t​o​s​!
	 */
	toastFavAdded: string
	/**
	 * P​r​e​f​e​r​e​n​c​i​a​s​ ​g​u​a​r​d​a​d​a​s​:​ ​M​o​s​t​r​a​n​d​o​ ​{​c​a​t​e​g​o​r​y​}​.
	 * @param {unknown} category
	 */
	toastPrefsSaved: RequiredParams<'category'>
	/**
	 * S​e​s​i​ó​n​ ​c​e​r​r​a​d​a​ ​c​o​r​r​e​c​t​a​m​e​n​t​e​.​ ​¡​V​u​e​l​v​e​ ​p​r​o​n​t​o​!
	 */
	toastSignoutSuccess: string
	/**
	 * H​u​b​o​ ​u​n​ ​p​r​o​b​l​e​m​a​ ​a​l​ ​c​e​r​r​a​r​ ​t​u​ ​s​e​s​i​ó​n​.
	 */
	toastSignoutError: string
	/**
	 * ¡​R​e​s​e​r​v​a​ ​c​o​m​p​l​e​t​a​d​a​ ​c​o​n​ ​é​x​i​t​o​!
	 */
	toastReservationSuccess: string
	/**
	 * I​n​t​e​l​l​i​g​e​n​t​ ​A​s​s​i​s​t​a​n​t
	 */
	planningModalKicker: string
	/**
	 * R​e​c​o​m​e​n​d​a​r​ ​P​a​n​o​r​a​m​a​s
	 */
	planningModalTitle: string
	/**
	 * I​n​d​i​c​a​ ​c​u​á​n​d​o​ ​r​e​a​l​i​z​a​r​á​s​ ​l​a​ ​a​c​t​i​v​i​d​a​d​ ​p​a​r​a​ ​q​u​e​ ​e​l​ ​s​i​s​t​e​m​a​ ​c​a​l​c​u​l​e​ ​l​a​s​ ​m​e​j​o​r​e​s​ ​o​p​c​i​o​n​e​s​ ​d​e​ ​f​o​r​m​a​ ​a​u​t​o​m​á​t​i​c​a​.
	 */
	planningModalDescription: string
	/**
	 * ¿​C​u​á​n​d​o​ ​q​u​i​e​r​e​s​ ​r​e​a​l​i​z​a​r​ ​l​a​ ​a​c​t​i​v​i​d​a​d​?
	 */
	whenQuestion: string
	/**
	 * H​o​y​ ​☀​️
	 */
	todayOptionCta: string
	/**
	 * O​t​r​o​ ​d​í​a​ ​�​�
	 */
	otherDayOptionCta: string
	/**
	 * S​e​l​e​c​c​i​o​n​a​ ​l​a​ ​f​e​c​h​a
	 */
	selectDateLabel: string
	/**
	 * ¿​A​ ​q​u​é​ ​h​o​r​a​ ​e​s​t​i​m​a​s​ ​i​r​?
	 */
	whatTimeQuestion: string
	/**
	 * C​u​a​l​q​u​i​e​r​ ​h​o​r​a​ ​�​�
	 */
	anyTimeOptionCta: string
	/**
	 * H​o​r​a​ ​e​s​p​e​c​í​f​i​c​a​ ​⚡
	 */
	specificTimeOptionCta: string
	/**
	 * D​e​f​i​n​e​ ​l​a​ ​h​o​r​a​ ​e​s​p​e​c​í​f​i​c​a
	 */
	specificTimeLabel: string
	/**
	 * O​b​t​e​n​e​r​ ​R​e​c​o​m​e​n​d​a​c​i​ó​n​ ​�​�
	 */
	getRecommendationCta: string
	/**
	 * #​1​ ​R​e​c​o​m​e​n​d​a​d​o
	 */
	rank1Label: string
	/**
	 * #​2​ ​R​e​c​o​m​e​n​d​a​d​o
	 */
	rank2Label: string
	/**
	 * #​3​ ​R​e​c​o​m​e​n​d​a​d​o
	 */
	rank3Label: string
	/**
	 * R​e​c​o​m​e​n​d​a​d​o
	 */
	recommendedLabel: string
	adminFormSectionPanoramaData: string
	adminFormImageLabel: string
	adminFormImagePlaceholder: string
	adminFormImageHint: string
	adminFormNameLabel: string
	adminFormNamePlaceholder: string
	adminFormDescriptionLabel: string
	adminFormDescriptionPlaceholder: string
	adminFormWeatherTagLabel: string
	adminFormWeatherAllOption: string
	adminFormWeatherSunnyOption: string
	adminFormAddressLabel: string
	adminFormAddressPlaceholder: string
	adminFormGeoInfoHtml: string
	adminFormGeoInfoHint: string
	adminFormSchedulesSection: string
	adminFormAddDateCta: string
	adminFormDateLabel: string
	adminFormRemoveDateTitle: string
	adminFormStartLabel: string
	adminFormEndLabel: string
	adminFormRemoveSlotTitle: string
	adminFormAddSlotCta: string
	adminFormPriceSection: string
	adminFormPriceLabel: string
	adminFormPricePlaceholder: string
	adminFormSlotsLabel: string
	adminFormSlotsPlaceholder: string
	adminFormSlotsHint: string
	adminFormSavingCta: string
	adminFormSubmitCta: string
	adminFormPreviewPayloadTitle: string
	adminFormPreviewLabel: string
	adminWeatherSunnyShort: string
	adminWeatherAllShort: string
	adminFormScheduleTBD: string
	adminFormDetailPreviewLabel: string
	adminFormDescriptionFallback: string
	adminFormNoAddressValue: string
	adminFormMapPlaceholderText: string
	adminFormDistanceNote: string
	adminFormErrorCreating: string
	adminFormSuccessGeocoded: string
	adminFormSuccessNotGeocoded: string
	adminFormSaveErrorGeneric: string
	adminManageLoadError: string
	adminManageLoadErrorGeneric: string
	adminManageDeleteConfirm: RequiredParams<'name'>
	adminManageRegeoSuccess: RequiredParams<'n'>
	adminManageRegeoError: string
	adminManageGeocodingCta: string
	adminManageRegeocodeCta: string
	adminManageReloadCta: string
	adminManageEmptyCategory: string
	adminManageNoPrice: string
	adminManageAvailabilityTitle: string
	adminManageAvailableLabel: string
	adminManageUnavailableLabel: string
	adminManageDeleteTitle: string
}

export type TranslationFunctions = {
	/**
	 * Cargando...
	 */
	loading: () => LocalizedString
	/**
	 * Cargando panoramas…
	 */
	loadingPanoramas: () => LocalizedString
	/**
	 * Error
	 */
	errorPrefix: () => LocalizedString
	/**
	 * Error de conexión con el servidor
	 */
	serverError: () => LocalizedString
	/**
	 * Iniciar Sesión
	 */
	signIn: () => LocalizedString
	/**
	 * Registrarse
	 */
	register: () => LocalizedString
	/**
	 * Crear Cuenta
	 */
	createAccount: () => LocalizedString
	/**
	 * Continuar con Google
	 */
	continueWithGoogle: () => LocalizedString
	/**
	 * o
	 */
	or: () => LocalizedString
	/**
	 * Autenticación Segura (SSO + OTP)
	 */
	secureAuth: () => LocalizedString
	/**
	 * Nombre
	 */
	name: () => LocalizedString
	/**
	 * Email
	 */
	email: () => LocalizedString
	/**
	 * Contraseña
	 */
	password: () => LocalizedString
	/**
	 * Hubo un problema al conectar con Google.
	 */
	loginGoogleFailed: () => LocalizedString
	/**
	 * Credenciales incorrectas
	 */
	badCredentials: () => LocalizedString
	/**
	 * Error al crear la cuenta
	 */
	createAccountError: () => LocalizedString
	/**
	 * Mínimo 8 caracteres
	 */
	pwdMin8: () => LocalizedString
	/**
	 * Al menos 1 mayúscula
	 */
	pwdUppercase: () => LocalizedString
	/**
	 * Al menos 1 número
	 */
	pwdNumber: () => LocalizedString
	/**
	 * Al menos 1 carácter especial
	 */
	pwdSpecial: () => LocalizedString
	/**
	 * Verificación de Seguridad
	 */
	otpTitle: () => LocalizedString
	/**
	 * Ingresa el código de 6 dígitos para confirmar tu identidad.
	 */
	otpInstructions: () => LocalizedString
	/**
	 * Verificar Código
	 */
	otpVerify: () => LocalizedString
	/**
	 * Verificando...
	 */
	otpVerifying: () => LocalizedString
	/**
	 * Código incorrecto o expirado
	 */
	otpInvalid: () => LocalizedString
	/**
	 * Volver al inicio de sesión
	 */
	otpBackToLogin: () => LocalizedString
	/**
	 * Cerrar sesión
	 */
	logout: () => LocalizedString
	/**
	 * Panorama encontrado
	 */
	panoramaFound: () => LocalizedString
	/**
	 * Panoramas encontrados
	 */
	panoramasFound: () => LocalizedString
	/**
	 * No hay actividades publicadas para esta categoría todavía.
	 */
	emptyState: () => LocalizedString
	/**
	 * Filtros
	 */
	filters: () => LocalizedString
	/**
	 * Ver detalles
	 */
	seeDetails: () => LocalizedString
	/**
	 * ☀️ SOLEADO
	 */
	weatherSunny: () => LocalizedString
	/**
	 * ✨ TODO CLIMA
	 */
	weatherAll: () => LocalizedString
	/**
	 * Todas
	 */
	categoryAll: () => LocalizedString
	/**
	 * Cine
	 */
	categoryCine: () => LocalizedString
	/**
	 * Teatro
	 */
	categoryTeatro: () => LocalizedString
	/**
	 * Parque
	 */
	categoryParque: () => LocalizedString
	/**
	 * Museo
	 */
	categoryMuseo: () => LocalizedString
	/**
	 * Restaurante
	 */
	categoryRestaurante: () => LocalizedString
	/**
	 * Miradores
	 */
	categoryMiradores: () => LocalizedString
	/**
	 * Panel de Administrador
	 */
	adminPanel: () => LocalizedString
	/**
	 * ← Volver al inicio
	 */
	adminGoBack: () => LocalizedString
	/**
	 * ADMIN
	 */
	adminBadge: () => LocalizedString
	/**
	 * Admin
	 */
	adminAccessLink: () => LocalizedString
	/**
	 * Usuarios totales
	 */
	statTotalUsers: () => LocalizedString
	/**
	 * Actividades publicadas
	 */
	statTotalActivities: () => LocalizedString
	/**
	 * OTPs enviados hoy
	 */
	statOtpsSent: () => LocalizedString
	/**
	 * Categoría líder
	 */
	statTopCategory: () => LocalizedString
	/**
	 * Usuarios recientes
	 */
	sectionRecentUsers: () => LocalizedString
	/**
	 * Admins recientes
	 */
	recentAdmins: () => LocalizedString
	/**
	 * Usuarios recientes
	 */
	recentStandardUsers: () => LocalizedString
	/**
	 * Actividades por categoría
	 */
	sectionActivityByCategory: () => LocalizedString
	/**
	 * Email
	 */
	tableEmail: () => LocalizedString
	/**
	 * Rol
	 */
	tableRole: () => LocalizedString
	/**
	 * Registro
	 */
	tableJoined: () => LocalizedString
	/**
	 * Estado
	 */
	tableStatus: () => LocalizedString
	/**
	 * Admin
	 */
	roleAdmin: () => LocalizedString
	/**
	 * Usuario
	 */
	roleUser: () => LocalizedString
	/**
	 * Verificado
	 */
	statusActive: () => LocalizedString
	/**
	 * Pendiente
	 */
	statusPending: () => LocalizedString
	/**
	 * Error al actualizar el rol en la base de datos.
	 */
	roleUpdateError: () => LocalizedString
	/**
	 * Calculando tendencias...
	 */
	calculatingTrend: () => LocalizedString
	/**
	 * Reservar
	 */
	seeDetailsCta: () => LocalizedString
	/**
	 * Confirmar reserva
	 */
	reservationModalTitle: () => LocalizedString
	/**
	 * Vas a reservar este panorama. El pago se procesa al instante.
	 */
	reservationModalDescription: () => LocalizedString
	/**
	 * Confirmar y pagar
	 */
	reservationConfirmPay: () => LocalizedString
	/**
	 * Procesando pago…
	 */
	reservationProcessing: () => LocalizedString
	/**
	 * ¡Reserva confirmada!
	 */
	reservationSuccess: () => LocalizedString
	/**
	 * Podés verla en Mis Reservas.
	 */
	reservationSuccessHint: () => LocalizedString
	/**
	 * No pudimos procesar tu pago.
	 */
	reservationFailed: () => LocalizedString
	/**
	 * Cancelar
	 */
	reservationCancel: () => LocalizedString
	/**
	 * Cerrar
	 */
	reservationClose: () => LocalizedString
	/**
	 * ID Transacción
	 */
	transactionLabel: () => LocalizedString
	/**
	 * Mis Reservas
	 */
	myReservationsLink: () => LocalizedString
	/**
	 * Mis Reservas
	 */
	myReservationsTitle: () => LocalizedString
	/**
	 * Todavía no tenés reservas. Buscá un panorama y reservá.
	 */
	myReservationsEmpty: () => LocalizedString
	/**
	 * Cargando reservas…
	 */
	myReservationsLoading: () => LocalizedString
	/**
	 * Comprado
	 */
	reservationStatusComprado: () => LocalizedString
	/**
	 * Cancelado
	 */
	reservationStatusCancelado: () => LocalizedString
	/**
	 * Pendiente
	 */
	reservationStatusPendiente: () => LocalizedString
	/**
	 * Fecha de reserva
	 */
	reservationDate: () => LocalizedString
	/**
	 * Cancelar reserva
	 */
	reservationCancelAction: () => LocalizedString
	/**
	 * ¿Seguro que querés cancelar esta reserva?
	 */
	reservationCancelConfirm: () => LocalizedString
	/**
	 * Ver evento
	 */
	viewEventCta: () => LocalizedString
	/**
	 * Reservar
	 */
	reserveOnlyCta: () => LocalizedString
	/**
	 * Pagar ahora
	 */
	payNowCta: () => LocalizedString
	/**
	 * Pagar
	 */
	payButton: () => LocalizedString
	/**
	 * Reservar de nuevo
	 */
	rebookCta: () => LocalizedString
	/**
	 * ¡Reserva creada! Pendiente de pago.
	 */
	reservationCreatedPending: () => LocalizedString
	/**
	 * ¡Reserva confirmada y pagada!
	 */
	reservationCreatedPaid: () => LocalizedString
	/**
	 * Detalle del evento
	 */
	detailsModalTitle: () => LocalizedString
	/**
	 * Categoría
	 */
	detailsCategoryLabel: () => LocalizedString
	/**
	 * Clima recomendado
	 */
	detailsWeatherLabel: () => LocalizedString
	/**
	 * Horario
	 */
	detailsHoursLabel: () => LocalizedString
	/**
	 * Ubicación
	 */
	detailsCoordsLabel: () => LocalizedString
	/**
	 * Pagado
	 */
	reservationStatusPagado: () => LocalizedString
	/**
	 * Reservado (pendiente de pago)
	 */
	cardStatusPending: () => LocalizedString
	/**
	 * Comprado
	 */
	cardStatusPaid: () => LocalizedString
	/**
	 * Popular
	 */
	badgePopular: () => LocalizedString
	/**
	 * Tendencia
	 */
	badgeTendencia: () => LocalizedString
	/**
	 * Abierto: {open} - {close}
	 */
	openHours: (arg: { close: unknown, open: unknown }) => LocalizedString
	/**
	 * Afluencia: {level}
	 */
	occupancyLabel: (arg: { level: unknown }) => LocalizedString
	/**
	 * Alta
	 */
	occupancyHigh: () => LocalizedString
	/**
	 * Media
	 */
	occupancyMedium: () => LocalizedString
	/**
	 * Baja
	 */
	occupancyLow: () => LocalizedString
	/**
	 * Precio base
	 */
	priceLabel: () => LocalizedString
	/**
	 * Gratis
	 */
	free: () => LocalizedString
	/**
	 * No se pudo cargar la disponibilidad.
	 */
	availabilityLoadError: () => LocalizedString
	/**
	 * Clima Sugerido
	 */
	weatherSuggestedLabel: () => LocalizedString
	/**
	 * Ideal Exterior
	 */
	weatherIdealOutdoor: () => LocalizedString
	/**
	 * Apto Todo Clima
	 */
	weatherAllWeatherFit: () => LocalizedString
	/**
	 * Horario
	 */
	scheduleLabel: () => LocalizedString
	/**
	 * + costo de servicio al pagar
	 */
	serviceFeeNote: () => LocalizedString
	/**
	 * Distancia en auto
	 */
	drivingDistanceLabel: () => LocalizedString
	/**
	 * Distancia aproximada
	 */
	straightDistanceLabel: () => LocalizedString
	/**
	 * por carretera
	 */
	byRoad: () => LocalizedString
	/**
	 * en línea recta
	 */
	straightLine: () => LocalizedString
	/**
	 * Dirección
	 */
	addressLabel: () => LocalizedString
	/**
	 * Mapa del Lugar
	 */
	placeMapLabel: () => LocalizedString
	/**
	 * Sin ubicación
	 */
	noLocation: () => LocalizedString
	/**
	 * Elige fecha y horario
	 */
	chooseDateTime: () => LocalizedString
	/**
	 * Cargando disponibilidad...
	 */
	loadingAvailability: () => LocalizedString
	/**
	 * Este panorama no tiene fechas cargadas todavía.
	 */
	noDatesAvailable: () => LocalizedString
	/**
	 * cupos libres
	 */
	slotsFree: () => LocalizedString
	/**
	 * agotado
	 */
	soldOut: () => LocalizedString
	/**
	 * {n} cupos
	 */
	slotsCount: (arg: { n: unknown }) => LocalizedString
	/**
	 * Consultar fecha y hora
	 */
	checkDateTime: () => LocalizedString
	/**
	 * Pagar al tiro
	 */
	payRightNowCta: () => LocalizedString
	/**
	 * Volver al detalle
	 */
	backToDetailCta: () => LocalizedString
	/**
	 * Listo
	 */
	doneCta: () => LocalizedString
	/**
	 * No se pudo reservar
	 */
	reservationFailedGeneric: () => LocalizedString
	/**
	 * ¡Pago realizado! Reserva confirmada y cupo descontado.
	 */
	paymentDoneConfirmed: () => LocalizedString
	/**
	 * Reserva creada (pendiente de pago). Cupo descontado.
	 */
	reservationPendingSpotTaken: () => LocalizedString
	/**
	 * Error al reservar
	 */
	reservationErrorGeneric: () => LocalizedString
	/**
	 * 🧠 ¿Quieres recomendaciones personalizadas de panoramas?
	 */
	recommendBannerTitle: () => LocalizedString
	/**
	 * Encuentra las mejores opciones según el clima y horarios de hoy o de cualquier fecha que elijas.
	 */
	recommendBannerText: () => LocalizedString
	/**
	 * ✨ Recomendar Panoramas
	 */
	recommendBannerCta: () => LocalizedString
	/**
	 * 📅 Recomendación para Hoy Activa
	 */
	planningActiveTodayTitle: () => LocalizedString
	/**
	 * 📅 Recomendación Planificada Activa
	 */
	planningActiveFutureTitle: () => LocalizedString
	/**
	 * Mostrando panoramas ideales para
	 */
	planningTodayIntro: () => LocalizedString
	/**
	 * hoy
	 */
	today: () => LocalizedString
	/**
	 * en tiempo real.
	 */
	inRealTime: () => LocalizedString
	/**
	 * Clima detectado por API:
	 */
	weatherDetectedBy: () => LocalizedString
	/**
	 * Mostrando panoramas para el día
	 */
	planningFutureIntro: () => LocalizedString
	/**
	 * a las
	 */
	atTime: () => LocalizedString
	/**
	 * a cualquier hora
	 */
	anyTimeText: () => LocalizedString
	/**
	 * Clima estimado por API:
	 */
	weatherEstimatedBy: () => LocalizedString
	/**
	 * ☀️ Despejado
	 */
	weatherClear: () => LocalizedString
	/**
	 * ☁️ Nublado
	 */
	weatherCloudy: () => LocalizedString
	/**
	 * 🌧️ Lluvioso
	 */
	weatherRainy: () => LocalizedString
	/**
	 * 🔄 Volver al Tiempo Real
	 */
	backToRealTimeCta: () => LocalizedString
	/**
	 * Toda la región
	 */
	filterRadiusAll: () => LocalizedString
	/**
	 * A menos de 10km
	 */
	filterRadius10: () => LocalizedString
	/**
	 * A menos de 5km
	 */
	filterRadius5: () => LocalizedString
	/**
	 * A menos de 2km
	 */
	filterRadius2: () => LocalizedString
	/**
	 * Cualquier precio
	 */
	filterAnyPrice: () => LocalizedString
	/**
	 * Económico ($)
	 */
	filterPriceCheap: () => LocalizedString
	/**
	 * Moderado ($$)
	 */
	filterPriceModerate: () => LocalizedString
	/**
	 * Costoso ($$$)
	 */
	filterPriceExpensive: () => LocalizedString
	/**
	 * Muy Costoso ($$$$)
	 */
	filterPriceVeryExpensive: () => LocalizedString
	/**
	 * Gratis ($0)
	 */
	filterFreePrice: () => LocalizedString
	/**
	 * De pago
	 */
	filterPaidPrice: () => LocalizedString
	/**
	 * Solo Abiertos Ahora
	 */
	filterOpenNow: () => LocalizedString
	/**
	 * Buscando...
	 */
	searching: () => LocalizedString
	/**
	 * Aplicar Filtros
	 */
	applyFilters: () => LocalizedString
	/**
	 * No se pudo conectar con el servicio meteorológico.
	 */
	toastWeatherError: () => LocalizedString
	/**
	 * Eliminado de tus favoritos.
	 */
	toastFavRemoved: () => LocalizedString
	/**
	 * ¡Panorama guardado en tus favoritos!
	 */
	toastFavAdded: () => LocalizedString
	/**
	 * Preferencias guardadas: Mostrando {category}.
	 */
	toastPrefsSaved: (arg: { category: unknown }) => LocalizedString
	/**
	 * Sesión cerrada correctamente. ¡Vuelve pronto!
	 */
	toastSignoutSuccess: () => LocalizedString
	/**
	 * Hubo un problema al cerrar tu sesión.
	 */
	toastSignoutError: () => LocalizedString
	/**
	 * ¡Reserva completada con éxito!
	 */
	toastReservationSuccess: () => LocalizedString
	/**
	 * Intelligent Assistant
	 */
	planningModalKicker: () => LocalizedString
	/**
	 * Recomendar Panoramas
	 */
	planningModalTitle: () => LocalizedString
	/**
	 * Indica cuándo realizarás la actividad para que el sistema calcule las mejores opciones de forma automática.
	 */
	planningModalDescription: () => LocalizedString
	/**
	 * ¿Cuándo quieres realizar la actividad?
	 */
	whenQuestion: () => LocalizedString
	/**
	 * Hoy ☀️
	 */
	todayOptionCta: () => LocalizedString
	/**
	 * Otro día 📅
	 */
	otherDayOptionCta: () => LocalizedString
	/**
	 * Selecciona la fecha
	 */
	selectDateLabel: () => LocalizedString
	/**
	 * ¿A qué hora estimas ir?
	 */
	whatTimeQuestion: () => LocalizedString
	/**
	 * Cualquier hora 🕒
	 */
	anyTimeOptionCta: () => LocalizedString
	/**
	 * Hora específica ⚡
	 */
	specificTimeOptionCta: () => LocalizedString
	/**
	 * Define la hora específica
	 */
	specificTimeLabel: () => LocalizedString
	/**
	 * Obtener Recomendación 🚀
	 */
	getRecommendationCta: () => LocalizedString
	/**
	 * #1 Recomendado
	 */
	rank1Label: () => LocalizedString
	/**
	 * #2 Recomendado
	 */
	rank2Label: () => LocalizedString
	/**
	 * #3 Recomendado
	 */
	rank3Label: () => LocalizedString
	/**
	 * Recomendado
	 */
	recommendedLabel: () => LocalizedString
	adminFormSectionPanoramaData: () => LocalizedString
	adminFormImageLabel: () => LocalizedString
	adminFormImagePlaceholder: () => LocalizedString
	adminFormImageHint: () => LocalizedString
	adminFormNameLabel: () => LocalizedString
	adminFormNamePlaceholder: () => LocalizedString
	adminFormDescriptionLabel: () => LocalizedString
	adminFormDescriptionPlaceholder: () => LocalizedString
	adminFormWeatherTagLabel: () => LocalizedString
	adminFormWeatherAllOption: () => LocalizedString
	adminFormWeatherSunnyOption: () => LocalizedString
	adminFormAddressLabel: () => LocalizedString
	adminFormAddressPlaceholder: () => LocalizedString
	adminFormGeoInfoHtml: () => LocalizedString
	adminFormGeoInfoHint: () => LocalizedString
	adminFormSchedulesSection: () => LocalizedString
	adminFormAddDateCta: () => LocalizedString
	adminFormDateLabel: () => LocalizedString
	adminFormRemoveDateTitle: () => LocalizedString
	adminFormStartLabel: () => LocalizedString
	adminFormEndLabel: () => LocalizedString
	adminFormRemoveSlotTitle: () => LocalizedString
	adminFormAddSlotCta: () => LocalizedString
	adminFormPriceSection: () => LocalizedString
	adminFormPriceLabel: () => LocalizedString
	adminFormPricePlaceholder: () => LocalizedString
	adminFormSlotsLabel: () => LocalizedString
	adminFormSlotsPlaceholder: () => LocalizedString
	adminFormSlotsHint: () => LocalizedString
	adminFormSavingCta: () => LocalizedString
	adminFormSubmitCta: () => LocalizedString
	adminFormPreviewPayloadTitle: () => LocalizedString
	adminFormPreviewLabel: () => LocalizedString
	adminWeatherSunnyShort: () => LocalizedString
	adminWeatherAllShort: () => LocalizedString
	adminFormScheduleTBD: () => LocalizedString
	adminFormDetailPreviewLabel: () => LocalizedString
	adminFormDescriptionFallback: () => LocalizedString
	adminFormNoAddressValue: () => LocalizedString
	adminFormMapPlaceholderText: () => LocalizedString
	adminFormDistanceNote: () => LocalizedString
	adminFormErrorCreating: () => LocalizedString
	adminFormSuccessGeocoded: () => LocalizedString
	adminFormSuccessNotGeocoded: () => LocalizedString
	adminFormSaveErrorGeneric: () => LocalizedString
	adminManageLoadError: () => LocalizedString
	adminManageLoadErrorGeneric: () => LocalizedString
	adminManageDeleteConfirm: (arg: { name: unknown }) => LocalizedString
	adminManageRegeoSuccess: (arg: { n: unknown }) => LocalizedString
	adminManageRegeoError: () => LocalizedString
	adminManageGeocodingCta: () => LocalizedString
	adminManageRegeocodeCta: () => LocalizedString
	adminManageReloadCta: () => LocalizedString
	adminManageEmptyCategory: () => LocalizedString
	adminManageNoPrice: () => LocalizedString
	adminManageAvailabilityTitle: () => LocalizedString
	adminManageAvailableLabel: () => LocalizedString
	adminManageUnavailableLabel: () => LocalizedString
	adminManageDeleteTitle: () => LocalizedString
}

export type Formatters = {}
